/*
 * languages.js — gemeinsame Übersetzungsbibliothek für die Kartenwerkstatt.
 * Wird sowohl von MAP.html (Kartengenerator) als auch von index.html (Startseite) genutzt.
 *
 * Schlüssel für MAP.html: title, subtitle, generateBtn, downloadBtn, toggleSettingsBtn,
 *   copySettingsBtn, shareToggleBtn, applyPasteSettingsBtn, settingsCopied, settingsCopyError,
 *   pasteSettingsPrompt, pasteSettingsError, lblSeed, grpCastles, lblMainCastle, lblOutposts,
 *   lblNoOutposts, grpTerrain, lblMountains, lblSea, lblForest, lblDesert, grpRiver,
 *   lblGenerateRiver, lblBridges, grpMap, lblFields, grpMarkers, lblActionFields, lblMerchant,
 *   footer, mapWord, fieldsWord, pngError, options{...}
 * Schlüssel für index.html: dir, pageTitle, heading, indexSubtitle, indexFooter, description, buttonText
 * ("subtitle"/"footer" gehören zu MAP.html, "indexSubtitle"/"indexFooter" zur Startseite —
 *  bewusst getrennt, da beide Seiten unterschiedliche Texte dafür brauchen.)
 *
 * Neue Sprache hinzufügen: einen neuen Eintrag mit all diesen Feldern ergänzen.
 */
const LANGUAGES = {
  "ar": {
    "nativeName": "العربية",
    "title": "خريطة المملكة",
    "subtitle": "خريطة خيالية مرسومة يدويًا: تُنشأ عشوائيًا، مع جبال وبحر وغابة وصحراء ونهر – قابلة للتخصيص بالكامل حسب رغبتك.",
    "generateBtn": "⚔ إنشاء خريطة جديدة",
    "downloadBtn": "⬇ حفظ كصورة PNG",
    "toggleSettingsBtn": "⚙ الإعدادات",
    "lblSeed": "البذرة:",
    "grpCastles": "القلاع",
    "lblMainCastle": "القلعة الرئيسية",
    "lblOutposts": "المخافر",
    "lblNoOutposts": "بدون مخافر",
    "grpTerrain": "التضاريس",
    "lblMountains": "الجبال",
    "lblSea": "البحر",
    "lblForest": "الغابة",
    "lblDesert": "الصحراء",
    "grpRiver": "النهر",
    "lblGenerateRiver": "إنشاء نهر",
    "lblBridges": "الجسور",
    "grpMap": "الخريطة",
    "lblFields": "الحقول (100–10000)",
    "grpMarkers": "العلامات",
    "lblActionFields": "حقول الأحداث (كل 500)",
    "lblMerchant": "رقم حقل التاجر",
    "footer": "يتم إنشاء كل خريطة عشوائيًا من جديد – تختلف التضاريس والطرق ومواقع المخافر قليلاً.",
    "mapWord": "خريطة",
    "fieldsWord": "حقول",
    "pngError": "فشل تصدير PNG. بدلاً من ذلك: انقر بزر الماوس الأيمن على الخريطة ← \"حفظ الصورة باسم\".",
    "options": {
      "aus": "إيقاف",
      "mitte": "المنتصف",
      "oben": "أعلى",
      "unten": "أسفل",
      "links": "يسار",
      "rechts": "يمين",
      "oben-links": "أعلى يسار",
      "oben-rechts": "أعلى يمين",
      "unten-links": "أسفل يسار",
      "unten-rechts": "أسفل يمين"
    },
    "dir": "rtl",
    "pageTitle": "ورشة الخرائط",
    "heading": "D&D Helper",
    "indexSubtitle": "رحلتك تبدأ بخريطة",
    "indexFooter": "ورشة الخرائط",
    "description": "اصنع عالمك الخيالي الخاص — بجبال وغابات وأنهار ومستوطنات. كل خريطة فريدة وقابلة لإعادة الإنتاج وجاهزة لمغامرتك القادمة.",
    "buttonText": "إلى الخريطة"
  },
  "bg": {
    "nativeName": "Български",
    "title": "Карта на кралството",
    "subtitle": "Ръчно нарисувана фентъзи карта: генерирана на случаен принцип, с планини, море, гора, пустиня и река – напълно персонализируема по ваш вкус.",
    "generateBtn": "⚔ Генерирай нова карта",
    "downloadBtn": "⬇ Запази като PNG",
    "toggleSettingsBtn": "⚙ Настройки",
    "lblSeed": "Начално число:",
    "grpCastles": "Замъци",
    "lblMainCastle": "Главен замък",
    "lblOutposts": "Аванпостове",
    "lblNoOutposts": "без аванпостове",
    "grpTerrain": "Терен",
    "lblMountains": "Планини",
    "lblSea": "Море",
    "lblForest": "Гора",
    "lblDesert": "Пустиня",
    "grpRiver": "Река",
    "lblGenerateRiver": "Генерирай река",
    "lblBridges": "Мостове",
    "grpMap": "Карта",
    "lblFields": "Полета (100–10000)",
    "grpMarkers": "Маркери",
    "lblActionFields": "Полета за действие (на всеки 500)",
    "lblMerchant": "№ на търговско поле",
    "footer": "Всяка карта се генерира отново на случаен принцип – теренът, пътищата и разположението на аванпостовете варират леко.",
    "mapWord": "Карта",
    "fieldsWord": "полета",
    "pngError": "Експортът в PNG не бе успешен. Алтернативно: щракнете с десен бутон върху картата → \"Запази изображението като\".",
    "options": {
      "aus": "Изключено",
      "mitte": "Център",
      "oben": "Горе",
      "unten": "Долу",
      "links": "Ляво",
      "rechts": "Дясно",
      "oben-links": "Горе ляво",
      "oben-rechts": "Горе дясно",
      "unten-links": "Долу ляво",
      "unten-rechts": "Долу дясно"
    },
    "dir": "ltr",
    "pageTitle": "Работилница за Карти",
    "heading": "D&D Helper",
    "indexSubtitle": "Пътуването ти започва с карта",
    "indexFooter": "Работилница за Карти",
    "description": "Създай своя собствен фентъзи свят — с планини, гори, реки и селища. Всяка карта е уникална, възпроизводима и готова за следващото ти приключение.",
    "buttonText": "Към Картата"
  },
  "bn": {
    "nativeName": "বাংলা",
    "title": "রাজ্যের মানচিত্র",
    "subtitle": "হাতে আঁকা একটি কল্পনার মানচিত্র: এলোমেলোভাবে তৈরি, পাহাড়, সমুদ্র, বন, মরুভূমি এবং একটি নদী সহ – সম্পূর্ণভাবে আপনার পছন্দমতো কাস্টমাইজযোগ্য।",
    "generateBtn": "⚔ নতুন মানচিত্র তৈরি করুন",
    "downloadBtn": "⬇ PNG হিসাবে সংরক্ষণ করুন",
    "toggleSettingsBtn": "⚙ সেটিংস",
    "lblSeed": "সীড:",
    "grpCastles": "দুর্গ",
    "lblMainCastle": "প্রধান দুর্গ",
    "lblOutposts": "ফাঁড়ি",
    "lblNoOutposts": "কোনো ফাঁড়ি নেই",
    "grpTerrain": "ভূখণ্ড",
    "lblMountains": "পাহাড়",
    "lblSea": "সমুদ্র",
    "lblForest": "বন",
    "lblDesert": "মরুভূমি",
    "grpRiver": "নদী",
    "lblGenerateRiver": "নদী তৈরি করুন",
    "lblBridges": "সেতু",
    "grpMap": "মানচিত্র",
    "lblFields": "মাঠ (১০০–১০০০০)",
    "grpMarkers": "মার্কার",
    "lblActionFields": "কর্ম ক্ষেত্র (প্রতি ৫০০)",
    "lblMerchant": "বণিক ক্ষেত্র নম্বর",
    "footer": "প্রতিটি মানচিত্র এলোমেলোভাবে নতুন করে তৈরি করা হয় – ভূখণ্ড, পথ এবং ফাঁড়ির অবস্থান কিছুটা ভিন্ন হয়।",
    "mapWord": "মানচিত্র",
    "fieldsWord": "মাঠ",
    "pngError": "PNG এক্সপোর্ট ব্যর্থ হয়েছে। বিকল্পভাবে: মানচিত্রে ডান-ক্লিক করুন → \"চিত্র সংরক্ষণ করুন\"।",
    "options": {
      "aus": "বন্ধ",
      "mitte": "কেন্দ্র",
      "oben": "উপরে",
      "unten": "নিচে",
      "links": "বামে",
      "rechts": "ডানে",
      "oben-links": "উপরে বামে",
      "oben-rechts": "উপরে ডানে",
      "unten-links": "নিচে বামে",
      "unten-rechts": "নিচে ডানে"
    },
    "dir": "ltr",
    "pageTitle": "মানচিত্র কর্মশালা",
    "heading": "D&D Helper",
    "indexSubtitle": "তোমার যাত্রা শুরু হয় একটি মানচিত্র দিয়ে",
    "indexFooter": "মানচিত্র কর্মশালা",
    "description": "পাহাড়, বন, নদী এবং জনবসতি নিয়ে তৈরি করো তোমার নিজস্ব কল্পনার জগৎ। প্রতিটি মানচিত্র অনন্য, পুনরুৎপাদনযোগ্য এবং তোমার পরবর্তী অভিযানের জন্য প্রস্তুত।",
    "buttonText": "মানচিত্রে যান"
  },
  "ca": {
    "nativeName": "Català",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "applyPasteSettingsBtn": "✓ Apply",
    "settingsCopied": "✓ Copied!",
    "settingsCopyError": "Copy failed",
    "pasteSettingsPrompt": "Paste the link or code here:",
    "pasteSettingsError": "Invalid settings code.",
    "lblSeed": "Seed:",
    "grpCastles": "Castles",
    "lblMainCastle": "Main castle",
    "lblOutposts": "Outposts",
    "lblNoOutposts": "no outposts",
    "grpTerrain": "Terrain",
    "lblMountains": "Mountains",
    "lblSea": "Sea",
    "lblForest": "Forest",
    "lblDesert": "Desert",
    "grpRiver": "River",
    "lblGenerateRiver": "Generate river",
    "lblBridges": "Bridges",
    "grpMap": "Map",
    "lblFields": "Fields (100–10000)",
    "grpMarkers": "Markers",
    "lblActionFields": "Action fields (every 500)",
    "lblMerchant": "Merchant field no.",
    "footer": "Every map is randomly generated anew – terrain, paths and outpost placement vary slightly.",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "dir": "ltr",
    "pageTitle": "Taller de Mapes",
    "heading": "D&D Helper",
    "indexSubtitle": "El teu viatge comença amb un mapa",
    "indexFooter": "Taller de Mapes",
    "description": "Crea el teu propi món de fantasia — amb muntanyes, boscos, rius i assentaments. Cada mapa és únic, reproduïble i preparat per a la teva propera aventura.",
    "buttonText": "Anar al Mapa"
  },
  "cs": {
    "nativeName": "Čeština",
    "title": "Mapa království",
    "subtitle": "Ručně kreslená fantasy mapa: náhodně generovaná, s horami, mořem, lesem, pouští a řekou – zcela přizpůsobitelná podle vašich přání.",
    "generateBtn": "⚔ Vygenerovat novou mapu",
    "downloadBtn": "⬇ Uložit jako PNG",
    "toggleSettingsBtn": "⚙ Nastavení",
    "lblSeed": "Seed:",
    "grpCastles": "Hrady",
    "lblMainCastle": "Hlavní hrad",
    "lblOutposts": "Základny",
    "lblNoOutposts": "bez základen",
    "grpTerrain": "Terén",
    "lblMountains": "Hory",
    "lblSea": "Moře",
    "lblForest": "Les",
    "lblDesert": "Poušť",
    "grpRiver": "Řeka",
    "lblGenerateRiver": "Vygenerovat řeku",
    "lblBridges": "Mosty",
    "grpMap": "Mapa",
    "lblFields": "Pole (100–10000)",
    "grpMarkers": "Značky",
    "lblActionFields": "Akční pole (každých 500)",
    "lblMerchant": "Č. obchodního pole",
    "footer": "Každá mapa je znovu náhodně vygenerována – terén, cesty a umístění základen se mírně liší.",
    "mapWord": "Mapa",
    "fieldsWord": "polí",
    "pngError": "Export do PNG selhal. Alternativně: klikněte pravým tlačítkem na mapu → \"Uložit obrázek jako\".",
    "options": {
      "aus": "Vypnuto",
      "mitte": "Střed",
      "oben": "Nahoře",
      "unten": "Dole",
      "links": "Vlevo",
      "rechts": "Vpravo",
      "oben-links": "Nahoře vlevo",
      "oben-rechts": "Nahoře vpravo",
      "unten-links": "Dole vlevo",
      "unten-rechts": "Dole vpravo"
    },
    "dir": "ltr",
    "pageTitle": "Dílna Map",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvá cesta začíná mapou",
    "indexFooter": "Dílna Map",
    "description": "Vytvoř si vlastní fantasy svět — s horami, lesy, řekami a osadami. Každá mapa je jedinečná, reprodukovatelná a připravená na tvé další dobrodružství.",
    "buttonText": "K Mapě"
  },
  "da": {
    "nativeName": "Dansk",
    "title": "Kongerigets kort",
    "subtitle": "Et håndtegnet fantasikort: genereret tilfældigt, med bjerge, hav, skov, ørken og en flod – fuldt tilpasseligt efter dine ønsker.",
    "generateBtn": "⚔ Generer nyt kort",
    "downloadBtn": "⬇ Gem som PNG",
    "toggleSettingsBtn": "⚙ Indstillinger",
    "lblSeed": "Seed:",
    "grpCastles": "Slotte",
    "lblMainCastle": "Hovedslot",
    "lblOutposts": "Forposter",
    "lblNoOutposts": "ingen forposter",
    "grpTerrain": "Terræn",
    "lblMountains": "Bjerge",
    "lblSea": "Hav",
    "lblForest": "Skov",
    "lblDesert": "Ørken",
    "grpRiver": "Flod",
    "lblGenerateRiver": "Generer flod",
    "lblBridges": "Broer",
    "grpMap": "Kort",
    "lblFields": "Felter (100–10000)",
    "grpMarkers": "Markører",
    "lblActionFields": "Handlingsfelter (hver 500.)",
    "lblMerchant": "Handelsfelt nr.",
    "footer": "Hvert kort genereres tilfældigt på ny – terræn, veje og forposternes placering varierer en smule.",
    "mapWord": "Kort",
    "fieldsWord": "felter",
    "pngError": "PNG-eksport mislykkedes. Alternativt: højreklik på kortet → \"Gem billede som\".",
    "options": {
      "aus": "Fra",
      "mitte": "Midte",
      "oben": "Top",
      "unten": "Bund",
      "links": "Venstre",
      "rechts": "Højre",
      "oben-links": "Top venstre",
      "oben-rechts": "Top højre",
      "unten-links": "Bund venstre",
      "unten-rechts": "Bund højre"
    },
    "dir": "ltr",
    "pageTitle": "Kortværksted",
    "heading": "D&D Helper",
    "indexSubtitle": "Din rejse begynder med et kort",
    "indexFooter": "Kortværksted",
    "description": "Skab din egen fantasiverden — med bjerge, skove, floder og bosættelser. Hvert kort er unikt, reproducerbart og klar til dit næste eventyr.",
    "buttonText": "Til Kortet"
  },
  "de": {
    "nativeName": "Deutsch",
    "title": "Karte des Königreichs",
    "subtitle": "Eine handgezeichnete Fantasiekarte: zufällig generiert, mit Bergen, Meer, Wald, Wüste und Fluss – und komplett nach deinen Wünschen einstellbar.",
    "generateBtn": "⚔ Neue Karte erzeugen",
    "downloadBtn": "⬇ Als PNG speichern",
    "toggleSettingsBtn": "⚙ Einstellungen",
    "copySettingsBtn": "📋 Kopieren",
    "shareToggleBtn": "🔗 Teilen",
    "applyPasteSettingsBtn": "✓ Anwenden",
    "settingsCopied": "✓ Kopiert!",
    "settingsCopyError": "Kopieren fehlgeschlagen",
    "pasteSettingsPrompt": "Link oder Code hier einfügen:",
    "pasteSettingsError": "Ungültiger Einstellungscode.",
    "lblSeed": "Seed:",
    "grpCastles": "Burgen",
    "lblMainCastle": "Hauptburg",
    "lblOutposts": "Außenposten",
    "lblNoOutposts": "keine Außenposten",
    "grpTerrain": "Gelände",
    "lblMountains": "Gebirge",
    "lblSea": "Meer",
    "lblForest": "Wald",
    "lblDesert": "Wüste",
    "grpRiver": "Fluss",
    "lblGenerateRiver": "Fluss generieren",
    "lblBridges": "Brücken",
    "grpMap": "Karte",
    "lblFields": "Felder (100–10000)",
    "grpMarkers": "Marker",
    "lblActionFields": "Aktionsfelder (je 500er)",
    "lblMerchant": "Händlerfeld Nr.",
    "footer": "Jede Karte wird zufällig neu erzeugt – Gelände, Wege und Lage der Außenposten variieren leicht.",
    "mapWord": "Karte",
    "fieldsWord": "Felder",
    "pngError": "PNG-Export ist fehlgeschlagen. Alternativ: Rechtsklick auf die Karte → \"Grafik speichern unter\".",
    "options": {
      "aus": "Aus",
      "mitte": "Mitte",
      "oben": "Oben",
      "unten": "Unten",
      "links": "Links",
      "rechts": "Rechts",
      "oben-links": "Oben links",
      "oben-rechts": "Oben rechts",
      "unten-links": "Unten links",
      "unten-rechts": "Unten rechts"
    },
    "dir": "ltr",
    "pageTitle": "Kartenwerkstatt",
    "heading": "D&D Helper",
    "indexSubtitle": "Deine Reise beginnt mit einer Karte",
    "indexFooter": "Kartenwerkstatt",
    "description": "Erschaffe deine eigene Fantasiewelt — mit Bergen, Wäldern, Flüssen und Siedlungen. Jede Karte ist einzigartig, reproduzierbar und bereit für dein nächstes Abenteuer.",
    "buttonText": "Zur Karte"
  },
  "el": {
    "nativeName": "Ελληνικά",
    "title": "Χάρτης του Βασιλείου",
    "subtitle": "Ένας χειροποίητος φανταστικός χάρτης: δημιουργείται τυχαία, με βουνά, θάλασσα, δάσος, έρημο και ποτάμι – πλήρως προσαρμόσιμος στις επιθυμίες σας.",
    "generateBtn": "⚔ Δημιουργία νέου χάρτη",
    "downloadBtn": "⬇ Αποθήκευση ως PNG",
    "toggleSettingsBtn": "⚙ Ρυθμίσεις",
    "lblSeed": "Σπόρος:",
    "grpCastles": "Κάστρα",
    "lblMainCastle": "Κύριο κάστρο",
    "lblOutposts": "Φυλάκια",
    "lblNoOutposts": "χωρίς φυλάκια",
    "grpTerrain": "Έδαφος",
    "lblMountains": "Βουνά",
    "lblSea": "Θάλασσα",
    "lblForest": "Δάσος",
    "lblDesert": "Έρημος",
    "grpRiver": "Ποτάμι",
    "lblGenerateRiver": "Δημιουργία ποταμού",
    "lblBridges": "Γέφυρες",
    "grpMap": "Χάρτης",
    "lblFields": "Πεδία (100–10000)",
    "grpMarkers": "Δείκτες",
    "lblActionFields": "Πεδία δράσης (κάθε 500)",
    "lblMerchant": "Αρ. πεδίου εμπόρου",
    "footer": "Κάθε χάρτης δημιουργείται εκ νέου τυχαία – το έδαφος, τα μονοπάτια και η θέση των φυλακίων ποικίλλουν ελαφρώς.",
    "mapWord": "Χάρτης",
    "fieldsWord": "πεδία",
    "pngError": "Η εξαγωγή PNG απέτυχε. Εναλλακτικά: δεξί κλικ στον χάρτη → \"Αποθήκευση εικόνας ως\".",
    "options": {
      "aus": "Απενεργοποιημένο",
      "mitte": "Κέντρο",
      "oben": "Πάνω",
      "unten": "Κάτω",
      "links": "Αριστερά",
      "rechts": "Δεξιά",
      "oben-links": "Πάνω αριστερά",
      "oben-rechts": "Πάνω δεξιά",
      "unten-links": "Κάτω αριστερά",
      "unten-rechts": "Κάτω δεξιά"
    },
    "dir": "ltr",
    "pageTitle": "Εργαστήρι Χαρτών",
    "heading": "D&D Helper",
    "indexSubtitle": "Το ταξίδι σου ξεκινά με έναν χάρτη",
    "indexFooter": "Εργαστήρι Χαρτών",
    "description": "Δημιούργησε τον δικό σου φανταστικό κόσμο — με βουνά, δάση, ποτάμια και οικισμούς. Κάθε χάρτης είναι μοναδικός, αναπαραγώγιμος και έτοιμος για την επόμενή σου περιπέτεια.",
    "buttonText": "Στον Χάρτη"
  },
  "en": {
    "nativeName": "English",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "applyPasteSettingsBtn": "✓ Apply",
    "settingsCopied": "✓ Copied!",
    "settingsCopyError": "Copy failed",
    "pasteSettingsPrompt": "Paste the link or code here:",
    "pasteSettingsError": "Invalid settings code.",
    "lblSeed": "Seed:",
    "grpCastles": "Castles",
    "lblMainCastle": "Main castle",
    "lblOutposts": "Outposts",
    "lblNoOutposts": "no outposts",
    "grpTerrain": "Terrain",
    "lblMountains": "Mountains",
    "lblSea": "Sea",
    "lblForest": "Forest",
    "lblDesert": "Desert",
    "grpRiver": "River",
    "lblGenerateRiver": "Generate river",
    "lblBridges": "Bridges",
    "grpMap": "Map",
    "lblFields": "Fields (100–10000)",
    "grpMarkers": "Markers",
    "lblActionFields": "Action fields (every 500)",
    "lblMerchant": "Merchant field no.",
    "footer": "Every map is randomly generated anew – terrain, paths and outpost placement vary slightly.",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "dir": "ltr",
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "indexFooter": "Map Workshop",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map"
  },
  "es": {
    "nativeName": "Español",
    "title": "Mapa del Reino",
    "subtitle": "Un mapa de fantasía dibujado a mano: generado aleatoriamente, con montañas, mar, bosque, desierto y un río – totalmente personalizable a tu gusto.",
    "generateBtn": "⚔ Generar nuevo mapa",
    "downloadBtn": "⬇ Guardar como PNG",
    "toggleSettingsBtn": "⚙ Ajustes",
    "lblSeed": "Semilla:",
    "grpCastles": "Castillos",
    "lblMainCastle": "Castillo principal",
    "lblOutposts": "Puestos avanzados",
    "lblNoOutposts": "sin puestos avanzados",
    "grpTerrain": "Terreno",
    "lblMountains": "Montañas",
    "lblSea": "Mar",
    "lblForest": "Bosque",
    "lblDesert": "Desierto",
    "grpRiver": "Río",
    "lblGenerateRiver": "Generar río",
    "lblBridges": "Puentes",
    "grpMap": "Mapa",
    "lblFields": "Casillas (100–10000)",
    "grpMarkers": "Marcadores",
    "lblActionFields": "Casillas de acción (cada 500)",
    "lblMerchant": "N.º de casilla de mercader",
    "footer": "Cada mapa se genera aleatoriamente de nuevo – el terreno, los caminos y la ubicación de los puestos avanzados varían ligeramente.",
    "mapWord": "Mapa",
    "fieldsWord": "casillas",
    "pngError": "La exportación a PNG ha fallado. Alternativa: clic derecho en el mapa → \"Guardar imagen como\".",
    "options": {
      "aus": "Desactivado",
      "mitte": "Centro",
      "oben": "Arriba",
      "unten": "Abajo",
      "links": "Izquierda",
      "rechts": "Derecha",
      "oben-links": "Arriba izquierda",
      "oben-rechts": "Arriba derecha",
      "unten-links": "Abajo izquierda",
      "unten-rechts": "Abajo derecha"
    },
    "dir": "ltr",
    "pageTitle": "Taller de Mapas",
    "heading": "D&D Helper",
    "indexSubtitle": "Tu viaje comienza con un mapa",
    "indexFooter": "Taller de Mapas",
    "description": "Crea tu propio mundo de fantasía, con montañas, bosques, ríos y asentamientos. Cada mapa es único, reproducible y listo para tu próxima aventura.",
    "buttonText": "Ir al Mapa"
  },
  "et": {
    "nativeName": "Eesti",
    "title": "Kuningriigi kaart",
    "subtitle": "Käsitsi joonistatud fantaasiakaart: genereeritud juhuslikult, mägede, mere, metsa, kõrbe ja jõega – täielikult sinu soovi järgi kohandatav.",
    "generateBtn": "⚔ Loo uus kaart",
    "downloadBtn": "⬇ Salvesta PNG-na",
    "toggleSettingsBtn": "⚙ Seaded",
    "lblSeed": "Seeme:",
    "grpCastles": "Lossid",
    "lblMainCastle": "Pealoss",
    "lblOutposts": "Eelpostid",
    "lblNoOutposts": "eelpostideta",
    "grpTerrain": "Maastik",
    "lblMountains": "Mäed",
    "lblSea": "Meri",
    "lblForest": "Mets",
    "lblDesert": "Kõrb",
    "grpRiver": "Jõgi",
    "lblGenerateRiver": "Loo jõgi",
    "lblBridges": "Sillad",
    "grpMap": "Kaart",
    "lblFields": "Väljad (100–10000)",
    "grpMarkers": "Markerid",
    "lblActionFields": "Tegevusväljad (iga 500 järel)",
    "lblMerchant": "Kaupmehe välja nr",
    "footer": "Iga kaart luuakse juhuslikult uuesti – maastik, teed ja eelpostide asukoht varieeruvad veidi.",
    "mapWord": "Kaart",
    "fieldsWord": "välja",
    "pngError": "PNG eksportimine ebaõnnestus. Alternatiivina: paremklõps kaardil → \"Salvesta pilt nimega\".",
    "options": {
      "aus": "Väljas",
      "mitte": "Keskel",
      "oben": "Üleval",
      "unten": "All",
      "links": "Vasakul",
      "rechts": "Paremal",
      "oben-links": "Üleval vasakul",
      "oben-rechts": "Üleval paremal",
      "unten-links": "All vasakul",
      "unten-rechts": "All paremal"
    },
    "dir": "ltr",
    "pageTitle": "Kaartide Töökoda",
    "heading": "D&D Helper",
    "indexSubtitle": "Sinu teekond algab kaardiga",
    "indexFooter": "Kaartide Töökoda",
    "description": "Loo oma fantaasiamaailm — mägede, metsade, jõgede ja asulatega. Iga kaart on unikaalne, korratav ja valmis sinu järgmiseks seikluseks.",
    "buttonText": "Kaardile"
  },
  "eu": {
    "nativeName": "Euskara",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "applyPasteSettingsBtn": "✓ Apply",
    "settingsCopied": "✓ Copied!",
    "settingsCopyError": "Copy failed",
    "pasteSettingsPrompt": "Paste the link or code here:",
    "pasteSettingsError": "Invalid settings code.",
    "lblSeed": "Seed:",
    "grpCastles": "Castles",
    "lblMainCastle": "Main castle",
    "lblOutposts": "Outposts",
    "lblNoOutposts": "no outposts",
    "grpTerrain": "Terrain",
    "lblMountains": "Mountains",
    "lblSea": "Sea",
    "lblForest": "Forest",
    "lblDesert": "Desert",
    "grpRiver": "River",
    "lblGenerateRiver": "Generate river",
    "lblBridges": "Bridges",
    "grpMap": "Map",
    "lblFields": "Fields (100–10000)",
    "grpMarkers": "Markers",
    "lblActionFields": "Action fields (every 500)",
    "lblMerchant": "Merchant field no.",
    "footer": "Every map is randomly generated anew – terrain, paths and outpost placement vary slightly.",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "dir": "ltr",
    "pageTitle": "Mapa-tailerra",
    "heading": "D&D Helper",
    "indexSubtitle": "Zure bidaia mapa batekin hasten da",
    "indexFooter": "Mapa-tailerra",
    "description": "Sortu zeure fantasiazko mundua — mendiak, basoak, ibaiak eta herriguneak dituena. Mapa bakoitza bakarra, erreproduzigarria eta zure hurrengo abenturarako prest dago.",
    "buttonText": "Mapara Joan"
  },
  "fa": {
    "nativeName": "فارسی",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "applyPasteSettingsBtn": "✓ Apply",
    "settingsCopied": "✓ Copied!",
    "settingsCopyError": "Copy failed",
    "pasteSettingsPrompt": "Paste the link or code here:",
    "pasteSettingsError": "Invalid settings code.",
    "lblSeed": "Seed:",
    "grpCastles": "Castles",
    "lblMainCastle": "Main castle",
    "lblOutposts": "Outposts",
    "lblNoOutposts": "no outposts",
    "grpTerrain": "Terrain",
    "lblMountains": "Mountains",
    "lblSea": "Sea",
    "lblForest": "Forest",
    "lblDesert": "Desert",
    "grpRiver": "River",
    "lblGenerateRiver": "Generate river",
    "lblBridges": "Bridges",
    "grpMap": "Map",
    "lblFields": "Fields (100–10000)",
    "grpMarkers": "Markers",
    "lblActionFields": "Action fields (every 500)",
    "lblMerchant": "Merchant field no.",
    "footer": "Every map is randomly generated anew – terrain, paths and outpost placement vary slightly.",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "dir": "rtl",
    "pageTitle": "کارگاه نقشه",
    "heading": "D&D Helper",
    "indexSubtitle": "سفر تو با یک نقشه آغاز می‌شود",
    "indexFooter": "کارگاه نقشه",
    "description": "دنیای خیالی خودت را بساز — با کوه‌ها، جنگل‌ها، رودخانه‌ها و سکونتگاه‌ها. هر نقشه منحصربه‌فرد، قابل بازتولید و آماده ماجراجویی بعدی توست.",
    "buttonText": "برو به نقشه"
  },
  "fi": {
    "nativeName": "Suomi",
    "title": "Kuningaskunnan kartta",
    "subtitle": "Käsin piirretty fantasiakartta: satunnaisesti luotu, vuorineen, merineen, metsineen, aavikkoineen ja jokineen – täysin muokattavissa mieltymystesi mukaan.",
    "generateBtn": "⚔ Luo uusi kartta",
    "downloadBtn": "⬇ Tallenna PNG:nä",
    "toggleSettingsBtn": "⚙ Asetukset",
    "lblSeed": "Siemenluku:",
    "grpCastles": "Linnat",
    "lblMainCastle": "Päälinna",
    "lblOutposts": "Etuvartiot",
    "lblNoOutposts": "ei etuvartioita",
    "grpTerrain": "Maasto",
    "lblMountains": "Vuoret",
    "lblSea": "Meri",
    "lblForest": "Metsä",
    "lblDesert": "Aavikko",
    "grpRiver": "Joki",
    "lblGenerateRiver": "Luo joki",
    "lblBridges": "Sillat",
    "grpMap": "Kartta",
    "lblFields": "Ruudut (100–10000)",
    "grpMarkers": "Merkit",
    "lblActionFields": "Tapahtumaruudut (joka 500.)",
    "lblMerchant": "Kauppiaan ruudun nro",
    "footer": "Jokainen kartta luodaan satunnaisesti uudelleen – maasto, polut ja etuvartioiden sijainti vaihtelevat hieman.",
    "mapWord": "Kartta",
    "fieldsWord": "ruutua",
    "pngError": "PNG-vienti epäonnistui. Vaihtoehtoisesti: napsauta karttaa hiiren oikealla painikkeella → \"Tallenna kuva nimellä\".",
    "options": {
      "aus": "Pois",
      "mitte": "Keskellä",
      "oben": "Ylhäällä",
      "unten": "Alhaalla",
      "links": "Vasemmalla",
      "rechts": "Oikealla",
      "oben-links": "Ylhäällä vasemmalla",
      "oben-rechts": "Ylhäällä oikealla",
      "unten-links": "Alhaalla vasemmalla",
      "unten-rechts": "Alhaalla oikealla"
    },
    "dir": "ltr",
    "pageTitle": "Karttapaja",
    "heading": "D&D Helper",
    "indexSubtitle": "Matkasi alkaa kartasta",
    "indexFooter": "Karttapaja",
    "description": "Luo oma fantasiamaailmasi — vuorineen, metsineen, jokineen ja asutuksineen. Jokainen kartta on ainutlaatuinen, toistettavissa ja valmis seuraavaan seikkailuusi.",
    "buttonText": "Kartalle"
  },
  "fr": {
    "nativeName": "Français",
    "title": "Carte du Royaume",
    "subtitle": "Une carte de fantasy dessinée à la main : générée aléatoirement, avec montagnes, mer, forêt, désert et une rivière – entièrement personnalisable selon vos envies.",
    "generateBtn": "⚔ Générer une nouvelle carte",
    "downloadBtn": "⬇ Enregistrer en PNG",
    "toggleSettingsBtn": "⚙ Paramètres",
    "lblSeed": "Graine :",
    "grpCastles": "Châteaux",
    "lblMainCastle": "Château principal",
    "lblOutposts": "Avant-postes",
    "lblNoOutposts": "aucun avant-poste",
    "grpTerrain": "Terrain",
    "lblMountains": "Montagnes",
    "lblSea": "Mer",
    "lblForest": "Forêt",
    "lblDesert": "Désert",
    "grpRiver": "Rivière",
    "lblGenerateRiver": "Générer une rivière",
    "lblBridges": "Ponts",
    "grpMap": "Carte",
    "lblFields": "Cases (100–10000)",
    "grpMarkers": "Marqueurs",
    "lblActionFields": "Cases d'action (tous les 500)",
    "lblMerchant": "N° de case marchand",
    "footer": "Chaque carte est régénérée aléatoirement – le terrain, les chemins et l'emplacement des avant-postes varient légèrement.",
    "mapWord": "Carte",
    "fieldsWord": "cases",
    "pngError": "L'export PNG a échoué. Alternative : clic droit sur la carte → \"Enregistrer l'image sous\".",
    "options": {
      "aus": "Désactivé",
      "mitte": "Centre",
      "oben": "Haut",
      "unten": "Bas",
      "links": "Gauche",
      "rechts": "Droite",
      "oben-links": "Haut gauche",
      "oben-rechts": "Haut droite",
      "unten-links": "Bas gauche",
      "unten-rechts": "Bas droite"
    },
    "dir": "ltr",
    "pageTitle": "Atelier de Cartes",
    "heading": "D&D Helper",
    "indexSubtitle": "Ton voyage commence avec une carte",
    "indexFooter": "Atelier de Cartes",
    "description": "Crée ton propre monde fantastique — avec des montagnes, des forêts, des rivières et des colonies. Chaque carte est unique, reproductible et prête pour ta prochaine aventure.",
    "buttonText": "Voir la Carte"
  },
  "ga": {
    "nativeName": "Gaeilge",
    "title": "Léarscáil na Ríochta",
    "subtitle": "Léarscáil fantaisíochta lámhtharraingthe: gineadh go randamach, le sléibhte, farraige, foraois, fásach agus abhainn – inoiriúnaithe go hiomlán de réir do mhian.",
    "generateBtn": "⚔ Gin Léarscáil Nua",
    "downloadBtn": "⬇ Sábháil mar PNG",
    "toggleSettingsBtn": "⚙ Socruithe",
    "lblSeed": "Síol:",
    "grpCastles": "Caisleáin",
    "lblMainCastle": "Príomhchaisleán",
    "lblOutposts": "Urphoist",
    "lblNoOutposts": "gan urphoist",
    "grpTerrain": "Tír-raon",
    "lblMountains": "Sléibhte",
    "lblSea": "Farraige",
    "lblForest": "Foraois",
    "lblDesert": "Fásach",
    "grpRiver": "Abhainn",
    "lblGenerateRiver": "Gin abhainn",
    "lblBridges": "Droichid",
    "grpMap": "Léarscáil",
    "lblFields": "Páirceanna (100–10000)",
    "grpMarkers": "Marcóirí",
    "lblActionFields": "Páirceanna gnímh (gach 500)",
    "lblMerchant": "Uimhir páirc an cheannaí",
    "footer": "Gintear gach léarscáil as an nua go randamach – athraíonn an tír-raon, na cosáin agus suíomh na n-urphost beagán.",
    "mapWord": "Léarscáil",
    "fieldsWord": "páirceanna",
    "pngError": "Theip ar onnmhairiú PNG. Mar rogha eile: deaschliceáil ar an léarscáil → \"Sábháil an íomhá mar\".",
    "options": {
      "aus": "As",
      "mitte": "Lár",
      "oben": "Barr",
      "unten": "Bun",
      "links": "Clé",
      "rechts": "Deas",
      "oben-links": "Barr clé",
      "oben-rechts": "Barr deas",
      "unten-links": "Bun clé",
      "unten-rechts": "Bun deas"
    },
    "dir": "ltr",
    "pageTitle": "Ceardlann Léarscáileanna",
    "heading": "D&D Helper",
    "indexSubtitle": "Tosaíonn do thuras le léarscáil",
    "indexFooter": "Ceardlann Léarscáileanna",
    "description": "Cruthaigh do shaol fantaisíochta féin — le sléibhte, foraoisí, aibhneacha agus lonnaíochtaí. Tá gach léarscáil uathúil, in-atáirgthe agus réidh do d'eachtra eile.",
    "buttonText": "Chuig an Léarscáil"
  },
  "hi": {
    "nativeName": "हिन्दी",
    "title": "राज्य का नक्शा",
    "subtitle": "हाथ से बना काल्पनिक नक्शा: यादृच्छिक रूप से बनाया गया, पहाड़ों, समुद्र, जंगल, रेगिस्तान और एक नदी के साथ – पूरी तरह से आपकी पसंद के अनुसार अनुकूलन योग्य।",
    "generateBtn": "⚔ नया नक्शा बनाएं",
    "downloadBtn": "⬇ PNG के रूप में सहेजें",
    "toggleSettingsBtn": "⚙ सेटिंग्स",
    "lblSeed": "सीड:",
    "grpCastles": "किले",
    "lblMainCastle": "मुख्य किला",
    "lblOutposts": "चौकियां",
    "lblNoOutposts": "कोई चौकी नहीं",
    "grpTerrain": "भूभाग",
    "lblMountains": "पहाड़",
    "lblSea": "समुद्र",
    "lblForest": "जंगल",
    "lblDesert": "रेगिस्तान",
    "grpRiver": "नदी",
    "lblGenerateRiver": "नदी बनाएं",
    "lblBridges": "पुल",
    "grpMap": "नक्शा",
    "lblFields": "खेत (100–10000)",
    "grpMarkers": "मार्कर",
    "lblActionFields": "क्रिया क्षेत्र (हर 500)",
    "lblMerchant": "व्यापारी क्षेत्र संख्या",
    "footer": "हर नक्शा यादृच्छिक रूप से नया बनाया जाता है – भूभाग, रास्ते और चौकियों की स्थिति थोड़ी भिन्न होती है।",
    "mapWord": "नक्शा",
    "fieldsWord": "खेत",
    "pngError": "PNG निर्यात विफल रहा। वैकल्पिक रूप से: नक्शे पर राइट-क्लिक करें → \"छवि को इस रूप में सहेजें\"।",
    "options": {
      "aus": "बंद",
      "mitte": "केंद्र",
      "oben": "ऊपर",
      "unten": "नीचे",
      "links": "बाएं",
      "rechts": "दाएं",
      "oben-links": "ऊपर बाएं",
      "oben-rechts": "ऊपर दाएं",
      "unten-links": "नीचे बाएं",
      "unten-rechts": "नीचे दाएं"
    },
    "dir": "ltr",
    "pageTitle": "मानचित्र कार्यशाला",
    "heading": "D&D Helper",
    "indexSubtitle": "आपकी यात्रा एक मानचित्र से शुरू होती है",
    "indexFooter": "मानचित्र कार्यशाला",
    "description": "पहाड़ों, जंगलों, नदियों और बस्तियों के साथ अपनी खुद की काल्पनिक दुनिया बनाएं। हर मानचित्र अनोखा, पुनरुत्पादनीय और आपके अगले रोमांच के लिए तैयार है।",
    "buttonText": "मानचित्र पर जाएं"
  },
  "hr": {
    "nativeName": "Hrvatski",
    "title": "Karta kraljevstva",
    "subtitle": "Ručno crtana fantastična karta: generirana nasumično, s planinama, morem, šumom, pustinjom i rijekom – potpuno prilagodljiva vašim željama.",
    "generateBtn": "⚔ Generiraj novu kartu",
    "downloadBtn": "⬇ Spremi kao PNG",
    "toggleSettingsBtn": "⚙ Postavke",
    "lblSeed": "Sjeme:",
    "grpCastles": "Dvorci",
    "lblMainCastle": "Glavni dvorac",
    "lblOutposts": "Ispostave",
    "lblNoOutposts": "bez ispostava",
    "grpTerrain": "Teren",
    "lblMountains": "Planine",
    "lblSea": "More",
    "lblForest": "Šuma",
    "lblDesert": "Pustinja",
    "grpRiver": "Rijeka",
    "lblGenerateRiver": "Generiraj rijeku",
    "lblBridges": "Mostovi",
    "grpMap": "Karta",
    "lblFields": "Polja (100–10000)",
    "grpMarkers": "Oznake",
    "lblActionFields": "Akcijska polja (svakih 500)",
    "lblMerchant": "Br. trgovačkog polja",
    "footer": "Svaka karta se ponovno generira nasumično – teren, putevi i položaj ispostava malo variraju.",
    "mapWord": "Karta",
    "fieldsWord": "polja",
    "pngError": "Izvoz u PNG nije uspio. Alternativno: desni klik na kartu → \"Spremi sliku kao\".",
    "options": {
      "aus": "Isključeno",
      "mitte": "Sredina",
      "oben": "Gore",
      "unten": "Dolje",
      "links": "Lijevo",
      "rechts": "Desno",
      "oben-links": "Gore lijevo",
      "oben-rechts": "Gore desno",
      "unten-links": "Dolje lijevo",
      "unten-rechts": "Dolje desno"
    },
    "dir": "ltr",
    "pageTitle": "Radionica Karata",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoje putovanje počinje kartom",
    "indexFooter": "Radionica Karata",
    "description": "Stvori svoj vlastiti fantastični svijet — s planinama, šumama, rijekama i naseljima. Svaka karta je jedinstvena, reproducibilna i spremna za tvoju sljedeću pustolovinu.",
    "buttonText": "Na Kartu"
  },
  "hu": {
    "nativeName": "Magyar",
    "title": "A Királyság térképe",
    "subtitle": "Kézzel rajzolt fantasy térkép: véletlenszerűen generált, hegyekkel, tengerrel, erdővel, sivataggal és folyóval – teljesen az igényeid szerint testreszabható.",
    "generateBtn": "⚔ Új térkép generálása",
    "downloadBtn": "⬇ Mentés PNG-ként",
    "toggleSettingsBtn": "⚙ Beállítások",
    "lblSeed": "Seed:",
    "grpCastles": "Várak",
    "lblMainCastle": "Fő vár",
    "lblOutposts": "Előőrsök",
    "lblNoOutposts": "nincs előőrs",
    "grpTerrain": "Terep",
    "lblMountains": "Hegyek",
    "lblSea": "Tenger",
    "lblForest": "Erdő",
    "lblDesert": "Sivatag",
    "grpRiver": "Folyó",
    "lblGenerateRiver": "Folyó generálása",
    "lblBridges": "Hidak",
    "grpMap": "Térkép",
    "lblFields": "Mezők (100–10000)",
    "grpMarkers": "Jelölők",
    "lblActionFields": "Eseménymezők (minden 500.)",
    "lblMerchant": "Kereskedő mező száma",
    "footer": "Minden térkép véletlenszerűen újra generálódik – a terep, az utak és az előőrsök helyzete kissé eltér.",
    "mapWord": "Térkép",
    "fieldsWord": "mező",
    "pngError": "A PNG exportálása sikertelen volt. Alternatíva: jobb kattintás a térképre → \"Kép mentése másként\".",
    "options": {
      "aus": "Ki",
      "mitte": "Közép",
      "oben": "Fent",
      "unten": "Lent",
      "links": "Bal",
      "rechts": "Jobb",
      "oben-links": "Fent balra",
      "oben-rechts": "Fent jobbra",
      "unten-links": "Lent balra",
      "unten-rechts": "Lent jobbra"
    },
    "dir": "ltr",
    "pageTitle": "Térképműhely",
    "heading": "D&D Helper",
    "indexSubtitle": "Utazásod egy térképpel kezdődik",
    "indexFooter": "Térképműhely",
    "description": "Alkosd meg saját fantasyvilágodat — hegyekkel, erdőkkel, folyókkal és településekkel. Minden térkép egyedi, reprodukálható és készen áll a következő kalandodra.",
    "buttonText": "A Térképhez"
  },
  "id": {
    "nativeName": "Bahasa Indonesia",
    "title": "Peta Kerajaan",
    "subtitle": "Peta fantasi gambar tangan: dibuat secara acak, dengan gunung, laut, hutan, gurun, dan sungai – sepenuhnya dapat disesuaikan sesuai keinginan Anda.",
    "generateBtn": "⚔ Buat Peta Baru",
    "downloadBtn": "⬇ Simpan sebagai PNG",
    "toggleSettingsBtn": "⚙ Pengaturan",
    "lblSeed": "Seed:",
    "grpCastles": "Kastil",
    "lblMainCastle": "Kastil utama",
    "lblOutposts": "Pos terdepan",
    "lblNoOutposts": "tanpa pos terdepan",
    "grpTerrain": "Medan",
    "lblMountains": "Gunung",
    "lblSea": "Laut",
    "lblForest": "Hutan",
    "lblDesert": "Gurun",
    "grpRiver": "Sungai",
    "lblGenerateRiver": "Buat sungai",
    "lblBridges": "Jembatan",
    "grpMap": "Peta",
    "lblFields": "Petak (100–10000)",
    "grpMarkers": "Penanda",
    "lblActionFields": "Petak aksi (tiap 500)",
    "lblMerchant": "No. petak pedagang",
    "footer": "Setiap peta dibuat ulang secara acak – medan, jalur, dan lokasi pos terdepan sedikit bervariasi.",
    "mapWord": "Peta",
    "fieldsWord": "petak",
    "pngError": "Ekspor PNG gagal. Alternatif: klik kanan pada peta → \"Simpan gambar sebagai\".",
    "options": {
      "aus": "Mati",
      "mitte": "Tengah",
      "oben": "Atas",
      "unten": "Bawah",
      "links": "Kiri",
      "rechts": "Kanan",
      "oben-links": "Atas kiri",
      "oben-rechts": "Atas kanan",
      "unten-links": "Bawah kiri",
      "unten-rechts": "Bawah kanan"
    },
    "dir": "ltr",
    "pageTitle": "Bengkel Peta",
    "heading": "D&D Helper",
    "indexSubtitle": "Perjalananmu dimulai dengan sebuah peta",
    "indexFooter": "Bengkel Peta",
    "description": "Ciptakan duniamu sendiri yang penuh fantasi — dengan gunung, hutan, sungai, dan pemukiman. Setiap peta unik, dapat direproduksi, dan siap untuk petualangan berikutnya.",
    "buttonText": "Ke Peta"
  },
  "is": {
    "nativeName": "Íslenska",
    "title": "Kort konungsríkisins",
    "subtitle": "Handteiknað ævintýrakort: búið til af handahófi, með fjöllum, hafi, skógi, eyðimörk og á – fullkomlega sérsniðið að þínum óskum.",
    "generateBtn": "⚔ Búa til nýtt kort",
    "downloadBtn": "⬇ Vista sem PNG",
    "toggleSettingsBtn": "⚙ Stillingar",
    "lblSeed": "Fræ:",
    "grpCastles": "Kastalar",
    "lblMainCastle": "Aðalkastali",
    "lblOutposts": "Útverðir",
    "lblNoOutposts": "engir útverðir",
    "grpTerrain": "Landslag",
    "lblMountains": "Fjöll",
    "lblSea": "Haf",
    "lblForest": "Skógur",
    "lblDesert": "Eyðimörk",
    "grpRiver": "Á",
    "lblGenerateRiver": "Búa til á",
    "lblBridges": "Brýr",
    "grpMap": "Kort",
    "lblFields": "Reitir (100–10000)",
    "grpMarkers": "Merki",
    "lblActionFields": "Atburðareitir (á 500 fresti)",
    "lblMerchant": "Nr. kaupmannsreits",
    "footer": "Hvert kort er búið til af handahófi á ný – landslag, slóðir og staðsetning útvarða eru örlítið breytileg.",
    "mapWord": "Kort",
    "fieldsWord": "reitir",
    "pngError": "PNG-útflutningur mistókst. Að öðrum kosti: hægrismelltu á kortið → \"Vista mynd sem\".",
    "options": {
      "aus": "Slökkt",
      "mitte": "Miðja",
      "oben": "Efst",
      "unten": "Neðst",
      "links": "Vinstri",
      "rechts": "Hægri",
      "oben-links": "Efst vinstri",
      "oben-rechts": "Efst hægri",
      "unten-links": "Neðst vinstri",
      "unten-rechts": "Neðst hægri"
    },
    "dir": "ltr",
    "pageTitle": "Kortasmiðja",
    "heading": "D&D Helper",
    "indexSubtitle": "Ferðalag þitt hefst með korti",
    "indexFooter": "Kortasmiðja",
    "description": "Skapaðu þinn eigin ævintýraheim — með fjöllum, skógum, ám og byggðum. Hvert kort er einstakt, endurskapanlegt og tilbúið fyrir næsta ævintýri þitt.",
    "buttonText": "Á Kortið"
  },
  "it": {
    "nativeName": "Italiano",
    "title": "Mappa del Regno",
    "subtitle": "Una mappa fantasy disegnata a mano: generata casualmente, con montagne, mare, foresta, deserto e un fiume – completamente personalizzabile a piacimento.",
    "generateBtn": "⚔ Genera nuova mappa",
    "downloadBtn": "⬇ Salva come PNG",
    "toggleSettingsBtn": "⚙ Impostazioni",
    "lblSeed": "Seme:",
    "grpCastles": "Castelli",
    "lblMainCastle": "Castello principale",
    "lblOutposts": "Avamposti",
    "lblNoOutposts": "nessun avamposto",
    "grpTerrain": "Terreno",
    "lblMountains": "Montagne",
    "lblSea": "Mare",
    "lblForest": "Foresta",
    "lblDesert": "Deserto",
    "grpRiver": "Fiume",
    "lblGenerateRiver": "Genera fiume",
    "lblBridges": "Ponti",
    "grpMap": "Mappa",
    "lblFields": "Caselle (100–10000)",
    "grpMarkers": "Indicatori",
    "lblActionFields": "Caselle azione (ogni 500)",
    "lblMerchant": "N. casella mercante",
    "footer": "Ogni mappa viene rigenerata casualmente – terreno, percorsi e posizione degli avamposti variano leggermente.",
    "mapWord": "Mappa",
    "fieldsWord": "caselle",
    "pngError": "Esportazione PNG non riuscita. In alternativa: clic destro sulla mappa → \"Salva immagine con nome\".",
    "options": {
      "aus": "Disattivato",
      "mitte": "Centro",
      "oben": "Sopra",
      "unten": "Sotto",
      "links": "Sinistra",
      "rechts": "Destra",
      "oben-links": "Sopra sinistra",
      "oben-rechts": "Sopra destra",
      "unten-links": "Sotto sinistra",
      "unten-rechts": "Sotto destra"
    },
    "dir": "ltr",
    "pageTitle": "Bottega delle Mappe",
    "heading": "D&D Helper",
    "indexSubtitle": "Il tuo viaggio inizia con una mappa",
    "indexFooter": "Bottega delle Mappe",
    "description": "Crea il tuo mondo fantastico — con montagne, foreste, fiumi e insediamenti. Ogni mappa è unica, riproducibile e pronta per la tua prossima avventura.",
    "buttonText": "Vai alla Mappa"
  },
  "ja": {
    "nativeName": "日本語",
    "title": "王国の地図",
    "subtitle": "手描きのファンタジーマップ：ランダムに生成され、山、海、森、砂漠、川があり、お好みに合わせて完全にカスタマイズ可能です。",
    "generateBtn": "⚔ 新しい地図を生成",
    "downloadBtn": "⬇ PNGとして保存",
    "toggleSettingsBtn": "⚙ 設定",
    "lblSeed": "シード：",
    "grpCastles": "城",
    "lblMainCastle": "メインの城",
    "lblOutposts": "前哨基地",
    "lblNoOutposts": "前哨基地なし",
    "grpTerrain": "地形",
    "lblMountains": "山",
    "lblSea": "海",
    "lblForest": "森",
    "lblDesert": "砂漠",
    "grpRiver": "川",
    "lblGenerateRiver": "川を生成",
    "lblBridges": "橋",
    "grpMap": "地図",
    "lblFields": "マス（100〜10000）",
    "grpMarkers": "マーカー",
    "lblActionFields": "アクションマス（500ごと）",
    "lblMerchant": "商人マス番号",
    "footer": "地図はランダムに新しく生成されます – 地形、道、前哨基地の位置は少しずつ異なります。",
    "mapWord": "地図",
    "fieldsWord": "マス",
    "pngError": "PNGのエクスポートに失敗しました。代わりに地図を右クリック →「名前を付けて画像を保存」をお試しください。",
    "options": {
      "aus": "オフ",
      "mitte": "中央",
      "oben": "上",
      "unten": "下",
      "links": "左",
      "rechts": "右",
      "oben-links": "左上",
      "oben-rechts": "右上",
      "unten-links": "左下",
      "unten-rechts": "右下"
    },
    "dir": "ltr",
    "pageTitle": "地図工房",
    "heading": "D&D Helper",
    "indexSubtitle": "あなたの旅は一枚の地図から始まる",
    "indexFooter": "地図工房",
    "description": "山、森、川、集落を備えた、あなただけのファンタジー世界を創り出そう。すべての地図は唯一無二でありながら再現可能。次の冒険への準備は整っている。",
    "buttonText": "地図を見る"
  },
  "ko": {
    "nativeName": "한국어",
    "title": "왕국 지도",
    "subtitle": "손으로 그린 판타지 지도: 무작위로 생성되며 산, 바다, 숲, 사막, 강이 있고 원하는 대로 완전히 사용자 지정할 수 있습니다.",
    "generateBtn": "⚔ 새 지도 생성",
    "downloadBtn": "⬇ PNG로 저장",
    "toggleSettingsBtn": "⚙ 설정",
    "lblSeed": "시드:",
    "grpCastles": "성",
    "lblMainCastle": "주성",
    "lblOutposts": "전초기지",
    "lblNoOutposts": "전초기지 없음",
    "grpTerrain": "지형",
    "lblMountains": "산",
    "lblSea": "바다",
    "lblForest": "숲",
    "lblDesert": "사막",
    "grpRiver": "강",
    "lblGenerateRiver": "강 생성",
    "lblBridges": "다리",
    "grpMap": "지도",
    "lblFields": "칸 (100–10000)",
    "grpMarkers": "마커",
    "lblActionFields": "이벤트 칸 (500개마다)",
    "lblMerchant": "상인 칸 번호",
    "footer": "모든 지도는 무작위로 새로 생성됩니다 – 지형, 경로, 전초기지 위치가 약간씩 달라집니다.",
    "mapWord": "지도",
    "fieldsWord": "칸",
    "pngError": "PNG 내보내기에 실패했습니다. 대신: 지도를 마우스 오른쪽 버튼으로 클릭 → \"이미지를 다른 이름으로 저장\"을 시도하세요.",
    "options": {
      "aus": "꺼짐",
      "mitte": "중앙",
      "oben": "위",
      "unten": "아래",
      "links": "왼쪽",
      "rechts": "오른쪽",
      "oben-links": "왼쪽 위",
      "oben-rechts": "오른쪽 위",
      "unten-links": "왼쪽 아래",
      "unten-rechts": "오른쪽 아래"
    },
    "dir": "ltr",
    "pageTitle": "지도 공방",
    "heading": "D&D Helper",
    "indexSubtitle": "당신의 여정은 지도 한 장에서 시작됩니다",
    "indexFooter": "지도 공방",
    "description": "산, 숲, 강, 정착지가 있는 나만의 판타지 세계를 만들어보세요. 모든 지도는 고유하며 재현 가능하고, 다음 모험을 위한 준비가 되어 있습니다.",
    "buttonText": "지도로 이동"
  },
  "lt": {
    "nativeName": "Lietuvių",
    "title": "Karalystės žemėlapis",
    "subtitle": "Ranka piešti fantastinis žemėlapis: sugeneruotas atsitiktinai, su kalnais, jūra, mišku, dykuma ir upe – visiškai pritaikomas pagal jūsų norus.",
    "generateBtn": "⚔ Generuoti naują žemėlapį",
    "downloadBtn": "⬇ Išsaugoti kaip PNG",
    "toggleSettingsBtn": "⚙ Nustatymai",
    "lblSeed": "Sėkla:",
    "grpCastles": "Pilys",
    "lblMainCastle": "Pagrindinė pilis",
    "lblOutposts": "Forpostai",
    "lblNoOutposts": "be forpostų",
    "grpTerrain": "Reljefas",
    "lblMountains": "Kalnai",
    "lblSea": "Jūra",
    "lblForest": "Miškas",
    "lblDesert": "Dykuma",
    "grpRiver": "Upė",
    "lblGenerateRiver": "Generuoti upę",
    "lblBridges": "Tiltai",
    "grpMap": "Žemėlapis",
    "lblFields": "Laukai (100–10000)",
    "grpMarkers": "Žymekliai",
    "lblActionFields": "Veiksmų laukai (kas 500)",
    "lblMerchant": "Prekybininko lauko nr.",
    "footer": "Kiekvienas žemėlapis generuojamas iš naujo atsitiktinai – reljefas, keliai ir forpostų vieta šiek tiek skiriasi.",
    "mapWord": "Žemėlapis",
    "fieldsWord": "laukai",
    "pngError": "PNG eksportavimas nepavyko. Alternatyviai: spustelėkite dešiniuoju pelės mygtuku ant žemėlapio → \"Išsaugoti paveikslėlį kaip\".",
    "options": {
      "aus": "Išjungta",
      "mitte": "Centras",
      "oben": "Viršuje",
      "unten": "Apačioje",
      "links": "Kairėje",
      "rechts": "Dešinėje",
      "oben-links": "Viršuje kairėje",
      "oben-rechts": "Viršuje dešinėje",
      "unten-links": "Apačioje kairėje",
      "unten-rechts": "Apačioje dešinėje"
    },
    "dir": "ltr",
    "pageTitle": "Žemėlapių Dirbtuvė",
    "heading": "D&D Helper",
    "indexSubtitle": "Tavo kelionė prasideda nuo žemėlapio",
    "indexFooter": "Žemėlapių Dirbtuvė",
    "description": "Sukurk savo fantastinį pasaulį — su kalnais, miškais, upėmis ir gyvenvietėmis. Kiekvienas žemėlapis yra unikalus, atkuriamas ir paruoštas tavo kitam nuotykiui.",
    "buttonText": "Į Žemėlapį"
  },
  "lv": {
    "nativeName": "Latviešu",
    "title": "Karalistes karte",
    "subtitle": "Ar roku zīmēta fantāzijas karte: izveidota nejauši, ar kalniem, jūru, mežu, tuksnesi un upi – pilnībā pielāgojama pēc jūsu vēlmēm.",
    "generateBtn": "⚔ Ģenerēt jaunu karti",
    "downloadBtn": "⬇ Saglabāt kā PNG",
    "toggleSettingsBtn": "⚙ Iestatījumi",
    "lblSeed": "Sēkla:",
    "grpCastles": "Pilis",
    "lblMainCastle": "Galvenā pils",
    "lblOutposts": "Priekšposteņi",
    "lblNoOutposts": "bez priekšposteņiem",
    "grpTerrain": "Reljefs",
    "lblMountains": "Kalni",
    "lblSea": "Jūra",
    "lblForest": "Mežs",
    "lblDesert": "Tuksnesis",
    "grpRiver": "Upe",
    "lblGenerateRiver": "Ģenerēt upi",
    "lblBridges": "Tilti",
    "grpMap": "Karte",
    "lblFields": "Lauki (100–10000)",
    "grpMarkers": "Marķieri",
    "lblActionFields": "Darbības lauki (ik pēc 500)",
    "lblMerchant": "Tirgotāja lauka Nr.",
    "footer": "Katra karte tiek ģenerēta no jauna nejauši – reljefs, ceļi un priekšposteņu atrašanās vieta nedaudz atšķiras.",
    "mapWord": "Karte",
    "fieldsWord": "lauki",
    "pngError": "PNG eksportēšana neizdevās. Alternatīvi: veiciet labo klikšķi uz kartes → \"Saglabāt attēlu kā\".",
    "options": {
      "aus": "Izslēgts",
      "mitte": "Centrs",
      "oben": "Augšā",
      "unten": "Apakšā",
      "links": "Kreisā",
      "rechts": "Labā",
      "oben-links": "Augšā kreisā",
      "oben-rechts": "Augšā labā",
      "unten-links": "Apakšā kreisā",
      "unten-rechts": "Apakšā labā"
    },
    "dir": "ltr",
    "pageTitle": "Karšu Darbnīca",
    "heading": "D&D Helper",
    "indexSubtitle": "Tavs ceļojums sākas ar karti",
    "indexFooter": "Karšu Darbnīca",
    "description": "Radi savu paša fantāzijas pasauli — ar kalniem, mežiem, upēm un apmetnēm. Katra karte ir unikāla, atkārtojama un gatava tavam nākamajam piedzīvojumam.",
    "buttonText": "Uz Karti"
  },
  "mr": {
    "nativeName": "मराठी",
    "title": "राज्याचा नकाशा",
    "subtitle": "हाताने काढलेला काल्पनिक नकाशा: यादृच्छिकपणे तयार केलेला, डोंगर, समुद्र, जंगल, वाळवंट आणि नदीसह – पूर्णपणे आपल्या आवडीनुसार सानुकूल करण्यायोग्य.",
    "generateBtn": "⚔ नवीन नकाशा तयार करा",
    "downloadBtn": "⬇ PNG म्हणून जतन करा",
    "toggleSettingsBtn": "⚙ सेटिंग्ज",
    "lblSeed": "सीड:",
    "grpCastles": "किल्ले",
    "lblMainCastle": "मुख्य किल्ला",
    "lblOutposts": "चौक्या",
    "lblNoOutposts": "चौक्या नाहीत",
    "grpTerrain": "भूभाग",
    "lblMountains": "डोंगर",
    "lblSea": "समुद्र",
    "lblForest": "जंगल",
    "lblDesert": "वाळवंट",
    "grpRiver": "नदी",
    "lblGenerateRiver": "नदी तयार करा",
    "lblBridges": "पूल",
    "grpMap": "नकाशा",
    "lblFields": "शेत (१००–१००००)",
    "grpMarkers": "चिन्हे",
    "lblActionFields": "क्रिया क्षेत्र (दर ५००)",
    "lblMerchant": "व्यापारी क्षेत्र क्रमांक",
    "footer": "प्रत्येक नकाशा यादृच्छिकपणे नव्याने तयार केला जातो – भूभाग, मार्ग आणि चौक्यांचे स्थान थोडे वेगळे असते.",
    "mapWord": "नकाशा",
    "fieldsWord": "शेत",
    "pngError": "PNG निर्यात अयशस्वी झाले. पर्यायाने: नकाशावर उजवे-क्लिक करा → \"प्रतिमा जतन करा\".",
    "options": {
      "aus": "बंद",
      "mitte": "मध्यभागी",
      "oben": "वर",
      "unten": "खाली",
      "links": "डावीकडे",
      "rechts": "उजवीकडे",
      "oben-links": "वर डावीकडे",
      "oben-rechts": "वर उजवीकडे",
      "unten-links": "खाली डावीकडे",
      "unten-rechts": "खाली उजवीकडे"
    },
    "dir": "ltr",
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "indexFooter": "Map Workshop",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map"
  },
  "mt": {
    "nativeName": "Malti",
    "title": "Mappa tas-Saltna",
    "subtitle": "Mappa fantażjuża miktuba bl-idejn: iġġenerata b'mod każwali, b'muntanji, baħar, foresta, deżert u xmara – kompletament tista' tiġi kkustomizzata skont ix-xewqat tiegħek.",
    "generateBtn": "⚔ Iġġenera Mappa Ġdida",
    "downloadBtn": "⬇ Issejvja bħala PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "lblSeed": "Seed:",
    "grpCastles": "Kastelli",
    "lblMainCastle": "Kastell prinċipali",
    "lblOutposts": "Postijiet avvanzati",
    "lblNoOutposts": "mingħajr postijiet avvanzati",
    "grpTerrain": "Terren",
    "lblMountains": "Muntanji",
    "lblSea": "Baħar",
    "lblForest": "Foresta",
    "lblDesert": "Deżert",
    "grpRiver": "Xmara",
    "lblGenerateRiver": "Iġġenera xmara",
    "lblBridges": "Pontijiet",
    "grpMap": "Mappa",
    "lblFields": "Oqsma (100–10000)",
    "grpMarkers": "Markaturi",
    "lblActionFields": "Oqsma ta' azzjoni (kull 500)",
    "lblMerchant": "Numru tal-qasam tan-negozjant",
    "footer": "Kull mappa tiġi ġġenerata mill-ġdid b'mod każwali – it-terren, il-mogħdijiet u l-pożizzjoni tal-postijiet avvanzati jvarjaw ftit.",
    "mapWord": "Mappa",
    "fieldsWord": "oqsma",
    "pngError": "L-esportazzjoni PNG falliet. Alternattivament: ikklikkja bil-lemin fuq il-mappa → \"Issejvja x-xbieha bħala\".",
    "options": {
      "aus": "Mitfi",
      "mitte": "Ċentru",
      "oben": "Fuq",
      "unten": "Isfel",
      "links": "Xellug",
      "rechts": "Lemin",
      "oben-links": "Fuq xellug",
      "oben-rechts": "Fuq lemin",
      "unten-links": "Isfel xellug",
      "unten-rechts": "Isfel lemin"
    },
    "dir": "ltr",
    "pageTitle": "Ħanut tal-Mapep",
    "heading": "D&D Helper",
    "indexSubtitle": "Il-vjaġġ tiegħek jibda b'mappa",
    "indexFooter": "Ħanut tal-Mapep",
    "description": "Ħoloq id-dinja fantastika tiegħek stess — b'muntanji, foresti, xmajjar u insedjamenti. Kull mappa hija unika, riproduċibbli u lesta għall-avventura li jmiss tiegħek.",
    "buttonText": "Mur għall-Mappa"
  },
  "nl": {
    "nativeName": "Nederlands",
    "title": "Kaart van het Koninkrijk",
    "subtitle": "Een handgetekende fantasiekaart: willekeurig gegenereerd, met bergen, zee, bos, woestijn en een rivier – volledig aanpasbaar naar wens.",
    "generateBtn": "⚔ Nieuwe kaart genereren",
    "downloadBtn": "⬇ Opslaan als PNG",
    "toggleSettingsBtn": "⚙ Instellingen",
    "lblSeed": "Seed:",
    "grpCastles": "Kastelen",
    "lblMainCastle": "Hoofdkasteel",
    "lblOutposts": "Buitenposten",
    "lblNoOutposts": "geen buitenposten",
    "grpTerrain": "Terrein",
    "lblMountains": "Bergen",
    "lblSea": "Zee",
    "lblForest": "Bos",
    "lblDesert": "Woestijn",
    "grpRiver": "Rivier",
    "lblGenerateRiver": "Rivier genereren",
    "lblBridges": "Bruggen",
    "grpMap": "Kaart",
    "lblFields": "Velden (100–10000)",
    "grpMarkers": "Markeringen",
    "lblActionFields": "Actievelden (elke 500)",
    "lblMerchant": "Handelaarsveld nr.",
    "footer": "Elke kaart wordt willekeurig opnieuw gegenereerd – terrein, paden en de ligging van buitenposten variëren licht.",
    "mapWord": "Kaart",
    "fieldsWord": "velden",
    "pngError": "PNG-export is mislukt. Alternatief: rechtsklik op de kaart → \"Afbeelding opslaan als\".",
    "options": {
      "aus": "Uit",
      "mitte": "Midden",
      "oben": "Boven",
      "unten": "Onder",
      "links": "Links",
      "rechts": "Rechts",
      "oben-links": "Boven links",
      "oben-rechts": "Boven rechts",
      "unten-links": "Onder links",
      "unten-rechts": "Onder rechts"
    },
    "dir": "ltr",
    "pageTitle": "Kaartenwerkplaats",
    "heading": "D&D Helper",
    "indexSubtitle": "Jouw reis begint met een kaart",
    "indexFooter": "Kaartenwerkplaats",
    "description": "Creëer je eigen fantasiewereld — met bergen, bossen, rivieren en nederzettingen. Elke kaart is uniek, reproduceerbaar en klaar voor je volgende avontuur.",
    "buttonText": "Naar de Kaart"
  },
  "no": {
    "nativeName": "Norsk",
    "title": "Kongerikets kart",
    "subtitle": "Et håndtegnet fantasikart: tilfeldig generert, med fjell, hav, skog, ørken og en elv – fullt tilpassbart etter dine ønsker.",
    "generateBtn": "⚔ Generer nytt kart",
    "downloadBtn": "⬇ Lagre som PNG",
    "toggleSettingsBtn": "⚙ Innstillinger",
    "lblSeed": "Frø:",
    "grpCastles": "Slott",
    "lblMainCastle": "Hovedslott",
    "lblOutposts": "Utposter",
    "lblNoOutposts": "ingen utposter",
    "grpTerrain": "Terreng",
    "lblMountains": "Fjell",
    "lblSea": "Hav",
    "lblForest": "Skog",
    "lblDesert": "Ørken",
    "grpRiver": "Elv",
    "lblGenerateRiver": "Generer elv",
    "lblBridges": "Broer",
    "grpMap": "Kart",
    "lblFields": "Felt (100–10000)",
    "grpMarkers": "Markører",
    "lblActionFields": "Handlingsfelt (hver 500.)",
    "lblMerchant": "Handelsfelt nr.",
    "footer": "Hvert kart genereres tilfeldig på ny – terreng, stier og utpostenes plassering varierer litt.",
    "mapWord": "Kart",
    "fieldsWord": "felt",
    "pngError": "PNG-eksport mislyktes. Alternativt: høyreklikk på kartet → \"Lagre bilde som\".",
    "options": {
      "aus": "Av",
      "mitte": "Midten",
      "oben": "Topp",
      "unten": "Bunn",
      "links": "Venstre",
      "rechts": "Høyre",
      "oben-links": "Topp venstre",
      "oben-rechts": "Topp høyre",
      "unten-links": "Bunn venstre",
      "unten-rechts": "Bunn høyre"
    },
    "dir": "ltr",
    "pageTitle": "Kartverksted",
    "heading": "D&D Helper",
    "indexSubtitle": "Reisen din begynner med et kart",
    "indexFooter": "Kartverksted",
    "description": "Skap din egen fantasiverden — med fjell, skoger, elver og bosetninger. Hvert kart er unikt, reproduserbart og klart for ditt neste eventyr.",
    "buttonText": "Til Kartet"
  },
  "pl": {
    "nativeName": "Polski",
    "title": "Mapa Królestwa",
    "subtitle": "Ręcznie rysowana mapa fantasy: generowana losowo, z górami, morzem, lasem, pustynią i rzeką – w pełni dostosowywana do Twoich upodobań.",
    "generateBtn": "⚔ Wygeneruj nową mapę",
    "downloadBtn": "⬇ Zapisz jako PNG",
    "toggleSettingsBtn": "⚙ Ustawienia",
    "lblSeed": "Ziarno:",
    "grpCastles": "Zamki",
    "lblMainCastle": "Główny zamek",
    "lblOutposts": "Placówki",
    "lblNoOutposts": "bez placówek",
    "grpTerrain": "Teren",
    "lblMountains": "Góry",
    "lblSea": "Morze",
    "lblForest": "Las",
    "lblDesert": "Pustynia",
    "grpRiver": "Rzeka",
    "lblGenerateRiver": "Wygeneruj rzekę",
    "lblBridges": "Mosty",
    "grpMap": "Mapa",
    "lblFields": "Pola (100–10000)",
    "grpMarkers": "Znaczniki",
    "lblActionFields": "Pola akcji (co 500)",
    "lblMerchant": "Nr pola kupca",
    "footer": "Każda mapa jest generowana od nowa losowo – teren, ścieżki i położenie placówek nieznacznie się różnią.",
    "mapWord": "Mapa",
    "fieldsWord": "pól",
    "pngError": "Eksport do PNG nie powiódł się. Alternatywnie: kliknij prawym przyciskiem myszy na mapie → \"Zapisz obraz jako\".",
    "options": {
      "aus": "Wyłączone",
      "mitte": "Środek",
      "oben": "Góra",
      "unten": "Dół",
      "links": "Lewo",
      "rechts": "Prawo",
      "oben-links": "Góra lewo",
      "oben-rechts": "Góra prawo",
      "unten-links": "Dół lewo",
      "unten-rechts": "Dół prawo"
    },
    "dir": "ltr",
    "pageTitle": "Pracownia Map",
    "heading": "D&D Helper",
    "indexSubtitle": "Twoja podróż zaczyna się od mapy",
    "indexFooter": "Pracownia Map",
    "description": "Stwórz własny fantastyczny świat — z górami, lasami, rzekami i osadami. Każda mapa jest unikalna, odtwarzalna i gotowa na twoją kolejną przygodę.",
    "buttonText": "Przejdź do Mapy"
  },
  "pt": {
    "nativeName": "Português",
    "title": "Mapa do Reino",
    "subtitle": "Um mapa de fantasia desenhado à mão: gerado aleatoriamente, com montanhas, mar, floresta, deserto e um rio – totalmente personalizável ao seu gosto.",
    "generateBtn": "⚔ Gerar novo mapa",
    "downloadBtn": "⬇ Salvar como PNG",
    "toggleSettingsBtn": "⚙ Configurações",
    "lblSeed": "Semente:",
    "grpCastles": "Castelos",
    "lblMainCastle": "Castelo principal",
    "lblOutposts": "Postos avançados",
    "lblNoOutposts": "sem postos avançados",
    "grpTerrain": "Terreno",
    "lblMountains": "Montanhas",
    "lblSea": "Mar",
    "lblForest": "Floresta",
    "lblDesert": "Deserto",
    "grpRiver": "Rio",
    "lblGenerateRiver": "Gerar rio",
    "lblBridges": "Pontes",
    "grpMap": "Mapa",
    "lblFields": "Campos (100–10000)",
    "grpMarkers": "Marcadores",
    "lblActionFields": "Campos de ação (a cada 500)",
    "lblMerchant": "Nº do campo do mercador",
    "footer": "Cada mapa é gerado aleatoriamente novamente – o terreno, os caminhos e a localização dos postos avançados variam ligeiramente.",
    "mapWord": "Mapa",
    "fieldsWord": "campos",
    "pngError": "A exportação para PNG falhou. Alternativa: clique com o botão direito no mapa → \"Salvar imagem como\".",
    "options": {
      "aus": "Desligado",
      "mitte": "Centro",
      "oben": "Cima",
      "unten": "Baixo",
      "links": "Esquerda",
      "rechts": "Direita",
      "oben-links": "Cima esquerda",
      "oben-rechts": "Cima direita",
      "unten-links": "Baixo esquerda",
      "unten-rechts": "Baixo direita"
    },
    "dir": "ltr",
    "pageTitle": "Oficina de Mapas",
    "heading": "D&D Helper",
    "indexSubtitle": "Sua jornada começa com um mapa",
    "indexFooter": "Oficina de Mapas",
    "description": "Crie o seu próprio mundo de fantasia — com montanhas, florestas, rios e assentamentos. Cada mapa é único, reproduzível e pronto para a sua próxima aventura.",
    "buttonText": "Ir para o Mapa"
  },
  "ro": {
    "nativeName": "Română",
    "title": "Harta Regatului",
    "subtitle": "O hartă fantastică desenată de mână: generată aleatoriu, cu munți, mare, pădure, deșert și un râu – complet personalizabilă după preferințele tale.",
    "generateBtn": "⚔ Generează o hartă nouă",
    "downloadBtn": "⬇ Salvează ca PNG",
    "toggleSettingsBtn": "⚙ Setări",
    "lblSeed": "Sămânță:",
    "grpCastles": "Castele",
    "lblMainCastle": "Castelul principal",
    "lblOutposts": "Avanposturi",
    "lblNoOutposts": "fără avanposturi",
    "grpTerrain": "Teren",
    "lblMountains": "Munți",
    "lblSea": "Mare",
    "lblForest": "Pădure",
    "lblDesert": "Deșert",
    "grpRiver": "Râu",
    "lblGenerateRiver": "Generează râu",
    "lblBridges": "Poduri",
    "grpMap": "Hartă",
    "lblFields": "Câmpuri (100–10000)",
    "grpMarkers": "Marcaje",
    "lblActionFields": "Câmpuri de acțiune (la fiecare 500)",
    "lblMerchant": "Nr. câmpului negustorului",
    "footer": "Fiecare hartă este regenerată aleatoriu – terenul, căile și poziția avanposturilor variază ușor.",
    "mapWord": "Hartă",
    "fieldsWord": "câmpuri",
    "pngError": "Exportul PNG a eșuat. Alternativ: click dreapta pe hartă → \"Salvează imaginea ca\".",
    "options": {
      "aus": "Dezactivat",
      "mitte": "Centru",
      "oben": "Sus",
      "unten": "Jos",
      "links": "Stânga",
      "rechts": "Dreapta",
      "oben-links": "Sus stânga",
      "oben-rechts": "Sus dreapta",
      "unten-links": "Jos stânga",
      "unten-rechts": "Jos dreapta"
    },
    "dir": "ltr",
    "pageTitle": "Atelierul de Hărți",
    "heading": "D&D Helper",
    "indexSubtitle": "Călătoria ta începe cu o hartă",
    "indexFooter": "Atelierul de Hărți",
    "description": "Creează-ți propria lume fantastică — cu munți, păduri, râuri și așezări. Fiecare hartă este unică, reproductibilă și pregătită pentru următoarea ta aventură.",
    "buttonText": "Spre Hartă"
  },
  "ru": {
    "nativeName": "Русский",
    "title": "Карта королевства",
    "subtitle": "Рисованная фэнтезийная карта: генерируется случайным образом, с горами, морем, лесом, пустыней и рекой — полностью настраивается по вашему желанию.",
    "generateBtn": "⚔ Создать новую карту",
    "downloadBtn": "⬇ Сохранить как PNG",
    "toggleSettingsBtn": "⚙ Настройки",
    "lblSeed": "Сид:",
    "grpCastles": "Замки",
    "lblMainCastle": "Главный замок",
    "lblOutposts": "Форпосты",
    "lblNoOutposts": "без форпостов",
    "grpTerrain": "Ландшафт",
    "lblMountains": "Горы",
    "lblSea": "Море",
    "lblForest": "Лес",
    "lblDesert": "Пустыня",
    "grpRiver": "Река",
    "lblGenerateRiver": "Создать реку",
    "lblBridges": "Мосты",
    "grpMap": "Карта",
    "lblFields": "Клетки (100–10000)",
    "grpMarkers": "Маркеры",
    "lblActionFields": "Клетки событий (каждые 500)",
    "lblMerchant": "№ клетки торговца",
    "footer": "Каждая карта генерируется заново случайным образом — ландшафт, пути и расположение форпостов немного отличаются.",
    "mapWord": "Карта",
    "fieldsWord": "клеток",
    "pngError": "Экспорт в PNG не удался. Альтернатива: щёлкните правой кнопкой по карте → \"Сохранить изображение как\".",
    "options": {
      "aus": "Выкл",
      "mitte": "Центр",
      "oben": "Сверху",
      "unten": "Снизу",
      "links": "Слева",
      "rechts": "Справа",
      "oben-links": "Сверху слева",
      "oben-rechts": "Сверху справа",
      "unten-links": "Снизу слева",
      "unten-rechts": "Снизу справа"
    },
    "dir": "ltr",
    "pageTitle": "Мастерская Карт",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоё путешествие начинается с карты",
    "indexFooter": "Мастерская Карт",
    "description": "Создай свой собственный фэнтезийный мир — с горами, лесами, реками и поселениями. Каждая карта уникальна, воспроизводима и готова для твоего следующего приключения.",
    "buttonText": "К Карте"
  },
  "sk": {
    "nativeName": "Slovenčina",
    "title": "Mapa kráľovstva",
    "subtitle": "Ručne kreslená fantasy mapa: náhodne generovaná, s horami, morom, lesom, púšťou a riekou – plne prispôsobiteľná podľa vašich predstáv.",
    "generateBtn": "⚔ Vygenerovať novú mapu",
    "downloadBtn": "⬇ Uložiť ako PNG",
    "toggleSettingsBtn": "⚙ Nastavenia",
    "lblSeed": "Seed:",
    "grpCastles": "Hrady",
    "lblMainCastle": "Hlavný hrad",
    "lblOutposts": "Základne",
    "lblNoOutposts": "bez základní",
    "grpTerrain": "Terén",
    "lblMountains": "Hory",
    "lblSea": "More",
    "lblForest": "Les",
    "lblDesert": "Púšť",
    "grpRiver": "Rieka",
    "lblGenerateRiver": "Vygenerovať rieku",
    "lblBridges": "Mosty",
    "grpMap": "Mapa",
    "lblFields": "Polia (100–10000)",
    "grpMarkers": "Značky",
    "lblActionFields": "Akčné polia (každých 500)",
    "lblMerchant": "Č. obchodného poľa",
    "footer": "Každá mapa sa znova náhodne vygeneruje – terén, cesty a umiestnenie základní sa mierne líšia.",
    "mapWord": "Mapa",
    "fieldsWord": "polí",
    "pngError": "Export do PNG zlyhal. Alternatívne: kliknite pravým tlačidlom na mapu → \"Uložiť obrázok ako\".",
    "options": {
      "aus": "Vypnuté",
      "mitte": "Stred",
      "oben": "Hore",
      "unten": "Dole",
      "links": "Vľavo",
      "rechts": "Vpravo",
      "oben-links": "Hore vľavo",
      "oben-rechts": "Hore vpravo",
      "unten-links": "Dole vľavo",
      "unten-rechts": "Dole vpravo"
    },
    "dir": "ltr",
    "pageTitle": "Dielňa Máp",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoja cesta začína mapou",
    "indexFooter": "Dielňa Máp",
    "description": "Vytvor si vlastný fantasy svet — s horami, lesmi, riekami a osadami. Každá mapa je jedinečná, reprodukovateľná a pripravená na tvoje ďalšie dobrodružstvo.",
    "buttonText": "K Mape"
  },
  "sl": {
    "nativeName": "Slovenščina",
    "title": "Zemljevid kraljestva",
    "subtitle": "Ročno narisan fantazijski zemljevid: naključno ustvarjen, z gorami, morjem, gozdom, puščavo in reko – v celoti prilagodljiv vašim željam.",
    "generateBtn": "⚔ Ustvari nov zemljevid",
    "downloadBtn": "⬇ Shrani kot PNG",
    "toggleSettingsBtn": "⚙ Nastavitve",
    "lblSeed": "Seme:",
    "grpCastles": "Gradovi",
    "lblMainCastle": "Glavni grad",
    "lblOutposts": "Postojanke",
    "lblNoOutposts": "brez postojank",
    "grpTerrain": "Teren",
    "lblMountains": "Gore",
    "lblSea": "Morje",
    "lblForest": "Gozd",
    "lblDesert": "Puščava",
    "grpRiver": "Reka",
    "lblGenerateRiver": "Ustvari reko",
    "lblBridges": "Mostovi",
    "grpMap": "Zemljevid",
    "lblFields": "Polja (100–10000)",
    "grpMarkers": "Oznake",
    "lblActionFields": "Akcijska polja (vsakih 500)",
    "lblMerchant": "Št. trgovskega polja",
    "footer": "Vsak zemljevid se ponovno naključno ustvari – teren, poti in lega postojank se rahlo razlikujejo.",
    "mapWord": "Zemljevid",
    "fieldsWord": "polj",
    "pngError": "Izvoz v PNG ni uspel. Druga možnost: desni klik na zemljevid → \"Shrani sliko kot\".",
    "options": {
      "aus": "Izklopljeno",
      "mitte": "Sredina",
      "oben": "Zgoraj",
      "unten": "Spodaj",
      "links": "Levo",
      "rechts": "Desno",
      "oben-links": "Zgoraj levo",
      "oben-rechts": "Zgoraj desno",
      "unten-links": "Spodaj levo",
      "unten-rechts": "Spodaj desno"
    },
    "dir": "ltr",
    "pageTitle": "Delavnica Zemljevidov",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoje potovanje se začne z zemljevidom",
    "indexFooter": "Delavnica Zemljevidov",
    "description": "Ustvari svoj lastni fantazijski svet — z gorami, gozdovi, rekami in naselji. Vsak zemljevid je edinstven, ponovljiv in pripravljen za tvojo naslednjo pustolovščino.",
    "buttonText": "Na Zemljevid"
  },
  "sq": {
    "nativeName": "Shqip",
    "title": "Harta e Mbretërisë",
    "subtitle": "Një hartë fantazie e vizatuar me dorë: e krijuar rastësisht, me male, det, pyll, shkretëtirë dhe një lumë – plotësisht e personalizueshme sipas dëshirës suaj.",
    "generateBtn": "⚔ Krijo hartë të re",
    "downloadBtn": "⬇ Ruaj si PNG",
    "toggleSettingsBtn": "⚙ Cilësimet",
    "lblSeed": "Fara:",
    "grpCastles": "Kështjella",
    "lblMainCastle": "Kështjella kryesore",
    "lblOutposts": "Postat e përparuara",
    "lblNoOutposts": "pa posta të përparuara",
    "grpTerrain": "Terreni",
    "lblMountains": "Male",
    "lblSea": "Det",
    "lblForest": "Pyll",
    "lblDesert": "Shkretëtirë",
    "grpRiver": "Lumi",
    "lblGenerateRiver": "Krijo lumë",
    "lblBridges": "Ura",
    "grpMap": "Harta",
    "lblFields": "Fusha (100–10000)",
    "grpMarkers": "Shënues",
    "lblActionFields": "Fusha veprimi (çdo 500)",
    "lblMerchant": "Nr. i fushës së tregtarit",
    "footer": "Çdo hartë krijohet rishtazi rastësisht – terreni, shtigjet dhe vendndodhja e postave të përparuara ndryshojnë pak.",
    "mapWord": "Harta",
    "fieldsWord": "fusha",
    "pngError": "Eksportimi PNG dështoi. Alternativa: klikoni me të djathtën mbi hartë → \"Ruaj imazhin si\".",
    "options": {
      "aus": "Fikur",
      "mitte": "Qendër",
      "oben": "Sipër",
      "unten": "Poshtë",
      "links": "Majtas",
      "rechts": "Djathtas",
      "oben-links": "Sipër majtas",
      "oben-rechts": "Sipër djathtas",
      "unten-links": "Poshtë majtas",
      "unten-rechts": "Poshtë djathtas"
    },
    "dir": "ltr",
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "indexFooter": "Map Workshop",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map"
  },
  "sr": {
    "nativeName": "Српски",
    "title": "Карта краљевства",
    "subtitle": "Ручно цртана фантастична карта: насумично генерисана, са планинама, морем, шумом, пустињом и реком – потпуно прилагодљива вашим жељама.",
    "generateBtn": "⚔ Генериши нову карту",
    "downloadBtn": "⬇ Сачувај као PNG",
    "toggleSettingsBtn": "⚙ Подешавања",
    "lblSeed": "Семе:",
    "grpCastles": "Замкови",
    "lblMainCastle": "Главни замак",
    "lblOutposts": "Испоставе",
    "lblNoOutposts": "без испостава",
    "grpTerrain": "Терен",
    "lblMountains": "Планине",
    "lblSea": "Море",
    "lblForest": "Шума",
    "lblDesert": "Пустиња",
    "grpRiver": "Река",
    "lblGenerateRiver": "Генериши реку",
    "lblBridges": "Мостови",
    "grpMap": "Карта",
    "lblFields": "Поља (100–10000)",
    "grpMarkers": "Ознаке",
    "lblActionFields": "Акциона поља (на сваких 500)",
    "lblMerchant": "Бр. трговачког поља",
    "footer": "Свака карта се поново насумично генерише – терен, путеви и положај испостава мало варирају.",
    "mapWord": "Карта",
    "fieldsWord": "поља",
    "pngError": "Извоз у PNG није успео. Алтернативно: десни клик на карту → \"Сачувај слику као\".",
    "options": {
      "aus": "Искључено",
      "mitte": "Средина",
      "oben": "Горе",
      "unten": "Доле",
      "links": "Лево",
      "rechts": "Десно",
      "oben-links": "Горе лево",
      "oben-rechts": "Горе десно",
      "unten-links": "Доле лево",
      "unten-rechts": "Доле десно"
    },
    "dir": "ltr",
    "pageTitle": "Radionica Mapa",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоје путовање почиње мапом",
    "indexFooter": "Radionica Mapa",
    "description": "Направи свој сопствени фантастични свет — са планинама, шумама, рекама и насељима. Свака мапа је јединствена, репродукована и спремна за твоју следећу авантуру.",
    "buttonText": "На Мапу"
  },
  "sv": {
    "nativeName": "Svenska",
    "title": "Kungarikets karta",
    "subtitle": "En handritad fantasikarta: slumpmässigt genererad, med berg, hav, skog, öken och en flod – helt anpassningsbar efter dina önskemål.",
    "generateBtn": "⚔ Generera ny karta",
    "downloadBtn": "⬇ Spara som PNG",
    "toggleSettingsBtn": "⚙ Inställningar",
    "lblSeed": "Frö:",
    "grpCastles": "Slott",
    "lblMainCastle": "Huvudslott",
    "lblOutposts": "Utposter",
    "lblNoOutposts": "inga utposter",
    "grpTerrain": "Terräng",
    "lblMountains": "Berg",
    "lblSea": "Hav",
    "lblForest": "Skog",
    "lblDesert": "Öken",
    "grpRiver": "Flod",
    "lblGenerateRiver": "Generera flod",
    "lblBridges": "Broar",
    "grpMap": "Karta",
    "lblFields": "Fält (100–10000)",
    "grpMarkers": "Markörer",
    "lblActionFields": "Händelsefält (var 500:e)",
    "lblMerchant": "Handelsfält nr.",
    "footer": "Varje karta genereras slumpmässigt på nytt – terräng, vägar och utposternas placering varierar något.",
    "mapWord": "Karta",
    "fieldsWord": "fält",
    "pngError": "PNG-export misslyckades. Alternativt: högerklicka på kartan → \"Spara bild som\".",
    "options": {
      "aus": "Av",
      "mitte": "Mitten",
      "oben": "Topp",
      "unten": "Botten",
      "links": "Vänster",
      "rechts": "Höger",
      "oben-links": "Topp vänster",
      "oben-rechts": "Topp höger",
      "unten-links": "Botten vänster",
      "unten-rechts": "Botten höger"
    },
    "dir": "ltr",
    "pageTitle": "Kartverkstad",
    "heading": "D&D Helper",
    "indexSubtitle": "Din resa börjar med en karta",
    "indexFooter": "Kartverkstad",
    "description": "Skapa din egen fantasyvärld — med berg, skogar, floder och bosättningar. Varje karta är unik, reproducerbar och redo för ditt nästa äventyr.",
    "buttonText": "Till Kartan"
  },
  "sw": {
    "nativeName": "Kiswahili",
    "title": "Ramani ya Ufalme",
    "subtitle": "Ramani ya kubuni iliyochorwa kwa mkono: inatengenezwa kwa nasibu, ikiwa na milima, bahari, msitu, jangwa na mto – inabadilishwa kikamilifu kulingana na matakwa yako.",
    "generateBtn": "⚔ Tengeneza Ramani Mpya",
    "downloadBtn": "⬇ Hifadhi kama PNG",
    "toggleSettingsBtn": "⚙ Mipangilio",
    "lblSeed": "Mbegu:",
    "grpCastles": "Ngome",
    "lblMainCastle": "Ngome kuu",
    "lblOutposts": "Vituo vya nje",
    "lblNoOutposts": "hakuna vituo vya nje",
    "grpTerrain": "Ardhi",
    "lblMountains": "Milima",
    "lblSea": "Bahari",
    "lblForest": "Msitu",
    "lblDesert": "Jangwa",
    "grpRiver": "Mto",
    "lblGenerateRiver": "Tengeneza mto",
    "lblBridges": "Madaraja",
    "grpMap": "Ramani",
    "lblFields": "Mashamba (100–10000)",
    "grpMarkers": "Alama",
    "lblActionFields": "Mashamba ya matukio (kila 500)",
    "lblMerchant": "Nambari ya shamba la mfanyabiashara",
    "footer": "Kila ramani hutengenezwa upya kwa nasibu – ardhi, njia na maeneo ya vituo vya nje hutofautiana kidogo.",
    "mapWord": "Ramani",
    "fieldsWord": "mashamba",
    "pngError": "Uhamishaji wa PNG umeshindwa. Vinginevyo: bofya kulia kwenye ramani → \"Hifadhi picha kama\".",
    "options": {
      "aus": "Imezimwa",
      "mitte": "Katikati",
      "oben": "Juu",
      "unten": "Chini",
      "links": "Kushoto",
      "rechts": "Kulia",
      "oben-links": "Juu kushoto",
      "oben-rechts": "Juu kulia",
      "unten-links": "Chini kushoto",
      "unten-rechts": "Chini kulia"
    },
    "dir": "ltr",
    "pageTitle": "Karakana ya Ramani",
    "heading": "D&D Helper",
    "indexSubtitle": "Safari yako inaanza na ramani",
    "indexFooter": "Karakana ya Ramani",
    "description": "Unda ulimwengu wako wa kubuni — wenye milima, misitu, mito na makazi. Kila ramani ni ya kipekee, inayoweza kutolewa tena, na tayari kwa ajili ya safari yako ijayo.",
    "buttonText": "Nenda kwenye Ramani"
  },
  "ta": {
    "nativeName": "தமிழ்",
    "title": "அரசின் வரைபடம்",
    "subtitle": "கையால் வரையப்பட்ட ஒரு கற்பனை வரைபடம்: சீரற்ற முறையில் உருவாக்கப்பட்டது, மலைகள், கடல், காடு, பாலைவனம் மற்றும் ஒரு ஆற்றுடன் – உங்கள் விருப்பத்திற்கு ஏற்ப முழுமையாக தனிப்பயனாக்கக்கூடியது.",
    "generateBtn": "⚔ புதிய வரைபடத்தை உருவாக்கு",
    "downloadBtn": "⬇ PNG ஆக சேமி",
    "toggleSettingsBtn": "⚙ அமைப்புகள்",
    "lblSeed": "விதை:",
    "grpCastles": "கோட்டைகள்",
    "lblMainCastle": "முதன்மை கோட்டை",
    "lblOutposts": "முன்னிலைகள்",
    "lblNoOutposts": "முன்னிலைகள் இல்லை",
    "grpTerrain": "நிலப்பரப்பு",
    "lblMountains": "மலைகள்",
    "lblSea": "கடல்",
    "lblForest": "காடு",
    "lblDesert": "பாலைவனம்",
    "grpRiver": "ஆறு",
    "lblGenerateRiver": "ஆற்றை உருவாக்கு",
    "lblBridges": "பாலங்கள்",
    "grpMap": "வரைபடம்",
    "lblFields": "வயல்கள் (100–10000)",
    "grpMarkers": "குறியீடுகள்",
    "lblActionFields": "செயல் வயல்கள் (ஒவ்வொரு 500)",
    "lblMerchant": "வணிகர் வயல் எண்",
    "footer": "ஒவ்வொரு வரைபடமும் சீரற்ற முறையில் மீண்டும் உருவாக்கப்படுகிறது – நிலப்பரப்பு, பாதைகள் மற்றும் முன்னிலைகளின் இடம் சற்று மாறுபடும்.",
    "mapWord": "வரைபடம்",
    "fieldsWord": "வயல்கள்",
    "pngError": "PNG ஏற்றுமதி தோல்வியடைந்தது. மாற்றாக: வரைபடத்தில் வலது கிளிக் செய்யவும் → \"படத்தை இப்படி சேமி\".",
    "options": {
      "aus": "ஆஃப்",
      "mitte": "மையம்",
      "oben": "மேலே",
      "unten": "கீழே",
      "links": "இடது",
      "rechts": "வலது",
      "oben-links": "மேலே இடது",
      "oben-rechts": "மேலே வலது",
      "unten-links": "கீழே இடது",
      "unten-rechts": "கீழே வலது"
    },
    "dir": "ltr",
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "indexFooter": "Map Workshop",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map"
  },
  "te": {
    "nativeName": "తెలుగు",
    "title": "రాజ్యం యొక్క పటం",
    "subtitle": "చేతితో గీసిన కల్పిత పటం: యాదృచ్ఛికంగా రూపొందించబడింది, పర్వతాలు, సముద్రం, అడవి, ఎడారి మరియు నదితో – మీ ఇష్టానికి అనుగుణంగా పూర్తిగా అనుకూలీకరించదగినది.",
    "generateBtn": "⚔ కొత్త పటం రూపొందించండి",
    "downloadBtn": "⬇ PNGగా సేవ్ చేయండి",
    "toggleSettingsBtn": "⚙ సెట్టింగ్‌లు",
    "lblSeed": "సీడ్:",
    "grpCastles": "కోటలు",
    "lblMainCastle": "ప్రధాన కోట",
    "lblOutposts": "అవుట్‌పోస్టులు",
    "lblNoOutposts": "అవుట్‌పోస్టులు లేవు",
    "grpTerrain": "భూభాగం",
    "lblMountains": "పర్వతాలు",
    "lblSea": "సముద్రం",
    "lblForest": "అడవి",
    "lblDesert": "ఎడారి",
    "grpRiver": "నది",
    "lblGenerateRiver": "నది సృష్టించండి",
    "lblBridges": "వంతెనలు",
    "grpMap": "పటం",
    "lblFields": "క్షేత్రాలు (100–10000)",
    "grpMarkers": "గుర్తులు",
    "lblActionFields": "చర్య క్షేత్రాలు (ప్రతి 500)",
    "lblMerchant": "వ్యాపారి క్షేత్ర సంఖ్య",
    "footer": "ప్రతి పటం యాదృచ్ఛికంగా కొత్తగా రూపొందించబడుతుంది – భూభాగం, మార్గాలు మరియు అవుట్‌పోస్టుల స్థానం కొద్దిగా మారుతుంది.",
    "mapWord": "పటం",
    "fieldsWord": "క్షేత్రాలు",
    "pngError": "PNG ఎగుమతి విఫలమైంది. ప్రత్యామ్నాయంగా: పటంపై కుడి-క్లిక్ చేయండి → \"చిత్రాన్ని ఇలా సేవ్ చేయండి\".",
    "options": {
      "aus": "ఆఫ్",
      "mitte": "మధ్య",
      "oben": "పైన",
      "unten": "కింద",
      "links": "ఎడమ",
      "rechts": "కుడి",
      "oben-links": "పైన ఎడమ",
      "oben-rechts": "పైన కుడి",
      "unten-links": "కింద ఎడమ",
      "unten-rechts": "కింద కుడి"
    },
    "dir": "ltr",
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "indexFooter": "Map Workshop",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map"
  },
  "th": {
    "nativeName": "ไทย",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "applyPasteSettingsBtn": "✓ Apply",
    "settingsCopied": "✓ Copied!",
    "settingsCopyError": "Copy failed",
    "pasteSettingsPrompt": "Paste the link or code here:",
    "pasteSettingsError": "Invalid settings code.",
    "lblSeed": "Seed:",
    "grpCastles": "Castles",
    "lblMainCastle": "Main castle",
    "lblOutposts": "Outposts",
    "lblNoOutposts": "no outposts",
    "grpTerrain": "Terrain",
    "lblMountains": "Mountains",
    "lblSea": "Sea",
    "lblForest": "Forest",
    "lblDesert": "Desert",
    "grpRiver": "River",
    "lblGenerateRiver": "Generate river",
    "lblBridges": "Bridges",
    "grpMap": "Map",
    "lblFields": "Fields (100–10000)",
    "grpMarkers": "Markers",
    "lblActionFields": "Action fields (every 500)",
    "lblMerchant": "Merchant field no.",
    "footer": "Every map is randomly generated anew – terrain, paths and outpost placement vary slightly.",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "dir": "ltr",
    "pageTitle": "โรงงานแผนที่",
    "heading": "D&D Helper",
    "indexSubtitle": "การเดินทางของคุณเริ่มต้นด้วยแผนที่",
    "indexFooter": "โรงงานแผนที่",
    "description": "สร้างโลกแฟนตาซีของคุณเอง — พร้อมภูเขา ป่าไม้ แม่น้ำ และถิ่นฐาน แผนที่ทุกแผ่นมีเอกลักษณ์เฉพาะตัว ทำซ้ำได้ และพร้อมสำหรับการผจญภัยครั้งต่อไปของคุณ",
    "buttonText": "ไปที่แผนที่"
  },
  "tr": {
    "nativeName": "Türkçe",
    "title": "Krallığın Haritası",
    "subtitle": "Elle çizilmiş bir fantezi haritası: rastgele oluşturulur, dağlar, deniz, orman, çöl ve bir nehir ile – tamamen isteğinize göre özelleştirilebilir.",
    "generateBtn": "⚔ Yeni Harita Oluştur",
    "downloadBtn": "⬇ PNG Olarak Kaydet",
    "toggleSettingsBtn": "⚙ Ayarlar",
    "lblSeed": "Tohum:",
    "grpCastles": "Kaleler",
    "lblMainCastle": "Ana kale",
    "lblOutposts": "Karakollar",
    "lblNoOutposts": "karakol yok",
    "grpTerrain": "Arazi",
    "lblMountains": "Dağlar",
    "lblSea": "Deniz",
    "lblForest": "Orman",
    "lblDesert": "Çöl",
    "grpRiver": "Nehir",
    "lblGenerateRiver": "Nehir oluştur",
    "lblBridges": "Köprüler",
    "grpMap": "Harita",
    "lblFields": "Alanlar (100–10000)",
    "grpMarkers": "İşaretler",
    "lblActionFields": "Eylem alanları (her 500'de bir)",
    "lblMerchant": "Tüccar alan no.",
    "footer": "Her harita rastgele olarak yeniden oluşturulur – arazi, yollar ve karakol konumları hafifçe değişir.",
    "mapWord": "Harita",
    "fieldsWord": "alan",
    "pngError": "PNG dışa aktarma başarısız oldu. Alternatif olarak: haritaya sağ tıklayın → \"Resmi farklı kaydet\".",
    "options": {
      "aus": "Kapalı",
      "mitte": "Merkez",
      "oben": "Üst",
      "unten": "Alt",
      "links": "Sol",
      "rechts": "Sağ",
      "oben-links": "Üst sol",
      "oben-rechts": "Üst sağ",
      "unten-links": "Alt sol",
      "unten-rechts": "Alt sağ"
    },
    "dir": "ltr",
    "pageTitle": "Harita Atölyesi",
    "heading": "D&D Helper",
    "indexSubtitle": "Yolculuğun bir haritayla başlıyor",
    "indexFooter": "Harita Atölyesi",
    "description": "Dağlar, ormanlar, nehirler ve yerleşimlerle kendi fantezi dünyanı yarat. Her harita benzersiz, tekrar üretilebilir ve bir sonraki maceran için hazır.",
    "buttonText": "Haritaya Git"
  },
  "uk": {
    "nativeName": "Українська",
    "title": "Карта королівства",
    "subtitle": "Мальована вручну фентезійна карта: генерується випадковим чином, з горами, морем, лісом, пустелею та річкою – повністю налаштовується за вашим бажанням.",
    "generateBtn": "⚔ Створити нову карту",
    "downloadBtn": "⬇ Зберегти як PNG",
    "toggleSettingsBtn": "⚙ Налаштування",
    "lblSeed": "Сід:",
    "grpCastles": "Замки",
    "lblMainCastle": "Головний замок",
    "lblOutposts": "Форпости",
    "lblNoOutposts": "без форпостів",
    "grpTerrain": "Ландшафт",
    "lblMountains": "Гори",
    "lblSea": "Море",
    "lblForest": "Ліс",
    "lblDesert": "Пустеля",
    "grpRiver": "Річка",
    "lblGenerateRiver": "Створити річку",
    "lblBridges": "Мости",
    "grpMap": "Карта",
    "lblFields": "Клітинки (100–10000)",
    "grpMarkers": "Маркери",
    "lblActionFields": "Клітинки подій (кожні 500)",
    "lblMerchant": "№ клітинки торговця",
    "footer": "Кожна карта генерується заново випадковим чином – ландшафт, шляхи та розташування форпостів трохи відрізняються.",
    "mapWord": "Карта",
    "fieldsWord": "клітинок",
    "pngError": "Експорт у PNG не вдався. Альтернатива: клацніть правою кнопкою миші по карті → \"Зберегти зображення як\".",
    "options": {
      "aus": "Вимкнено",
      "mitte": "Центр",
      "oben": "Зверху",
      "unten": "Знизу",
      "links": "Зліва",
      "rechts": "Справа",
      "oben-links": "Зверху зліва",
      "oben-rechts": "Зверху справа",
      "unten-links": "Знизу зліва",
      "unten-rechts": "Знизу справа"
    },
    "dir": "ltr",
    "pageTitle": "Майстерня Карт",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоя подорож починається з карти",
    "indexFooter": "Майстерня Карт",
    "description": "Створи власний фентезійний світ — з горами, лісами, річками та поселеннями. Кожна карта унікальна, відтворювана й готова до твоєї наступної пригоди.",
    "buttonText": "До Карти"
  },
  "ur": {
    "nativeName": "اردو",
    "title": "بادشاہی کا نقشہ",
    "subtitle": "ہاتھ سے بنایا گیا ایک فنتاسی نقشہ: بے ترتیب طور پر تیار کیا گیا، پہاڑوں، سمندر، جنگل، صحرا اور ایک دریا کے ساتھ – آپ کی مرضی کے مطابق مکمل طور پر قابل ترتیب۔",
    "generateBtn": "⚔ نیا نقشہ بنائیں",
    "downloadBtn": "⬇ PNG کے طور پر محفوظ کریں",
    "toggleSettingsBtn": "⚙ ترتیبات",
    "lblSeed": "سیڈ:",
    "grpCastles": "قلعے",
    "lblMainCastle": "مرکزی قلعہ",
    "lblOutposts": "چوکیاں",
    "lblNoOutposts": "کوئی چوکی نہیں",
    "grpTerrain": "خطہ",
    "lblMountains": "پہاڑ",
    "lblSea": "سمندر",
    "lblForest": "جنگل",
    "lblDesert": "صحرا",
    "grpRiver": "دریا",
    "lblGenerateRiver": "دریا بنائیں",
    "lblBridges": "پل",
    "grpMap": "نقشہ",
    "lblFields": "کھیت (100–10000)",
    "grpMarkers": "نشانات",
    "lblActionFields": "ایکشن کھیت (ہر 500)",
    "lblMerchant": "تاجر کھیت نمبر",
    "footer": "ہر نقشہ بے ترتیب طور پر نئے سرے سے بنایا جاتا ہے – خطہ، راستے اور چوکیوں کی جگہ قدرے مختلف ہوتی ہے۔",
    "mapWord": "نقشہ",
    "fieldsWord": "کھیت",
    "pngError": "PNG ایکسپورٹ ناکام ہو گیا۔ متبادل کے طور پر: نقشے پر دائیں کلک کریں → \"تصویر کو محفوظ کریں بطور\"۔",
    "options": {
      "aus": "بند",
      "mitte": "وسط",
      "oben": "اوپر",
      "unten": "نیچے",
      "links": "بائیں",
      "rechts": "دائیں",
      "oben-links": "اوپر بائیں",
      "oben-rechts": "اوپر دائیں",
      "unten-links": "نیچے بائیں",
      "unten-rechts": "نیچے دائیں"
    },
    "dir": "rtl",
    "pageTitle": "نقشہ ورکشاپ",
    "heading": "D&D Helper",
    "indexSubtitle": "آپ کا سفر ایک نقشے سے شروع ہوتا ہے",
    "indexFooter": "نقشہ ورکشاپ",
    "description": "پہاڑوں، جنگلات، دریاؤں اور بستیوں کے ساتھ اپنی خیالی دنیا بنائیں۔ ہر نقشہ منفرد، دوبارہ قابلِ تخلیق اور آپ کی اگلی مہم جوئی کے لیے تیار ہے۔",
    "buttonText": "نقشے پر جائیں"
  },
  "vi": {
    "nativeName": "Tiếng Việt",
    "title": "Bản đồ Vương quốc",
    "subtitle": "Một bản đồ giả tưởng được vẽ tay: được tạo ngẫu nhiên, với núi, biển, rừng, sa mạc và một con sông – hoàn toàn có thể tùy chỉnh theo ý thích của bạn.",
    "generateBtn": "⚔ Tạo Bản Đồ Mới",
    "downloadBtn": "⬇ Lưu dưới dạng PNG",
    "toggleSettingsBtn": "⚙ Cài đặt",
    "lblSeed": "Hạt giống:",
    "grpCastles": "Lâu đài",
    "lblMainCastle": "Lâu đài chính",
    "lblOutposts": "Tiền đồn",
    "lblNoOutposts": "không có tiền đồn",
    "grpTerrain": "Địa hình",
    "lblMountains": "Núi",
    "lblSea": "Biển",
    "lblForest": "Rừng",
    "lblDesert": "Sa mạc",
    "grpRiver": "Sông",
    "lblGenerateRiver": "Tạo sông",
    "lblBridges": "Cầu",
    "grpMap": "Bản đồ",
    "lblFields": "Ô (100–10000)",
    "grpMarkers": "Dấu hiệu",
    "lblActionFields": "Ô sự kiện (mỗi 500)",
    "lblMerchant": "Số ô thương nhân",
    "footer": "Mỗi bản đồ được tạo ngẫu nhiên lại từ đầu – địa hình, đường đi và vị trí tiền đồn thay đổi đôi chút.",
    "mapWord": "Bản đồ",
    "fieldsWord": "ô",
    "pngError": "Xuất PNG không thành công. Hoặc: nhấp chuột phải vào bản đồ → \"Lưu hình ảnh thành\".",
    "options": {
      "aus": "Tắt",
      "mitte": "Giữa",
      "oben": "Trên",
      "unten": "Dưới",
      "links": "Trái",
      "rechts": "Phải",
      "oben-links": "Trên trái",
      "oben-rechts": "Trên phải",
      "unten-links": "Dưới trái",
      "unten-rechts": "Dưới phải"
    },
    "dir": "ltr",
    "pageTitle": "Xưởng Bản Đồ",
    "heading": "D&D Helper",
    "indexSubtitle": "Hành trình của bạn bắt đầu với một tấm bản đồ",
    "indexFooter": "Xưởng Bản Đồ",
    "description": "Tạo nên thế giới giả tưởng của riêng bạn — với núi non, rừng rậm, sông ngòi và khu định cư. Mỗi bản đồ đều độc nhất, có thể tái tạo và sẵn sàng cho cuộc phiêu lưu tiếp theo.",
    "buttonText": "Đến Bản Đồ"
  },
  "zh": {
    "nativeName": "中文",
    "title": "王国地图",
    "subtitle": "一张手绘的奇幻地图：随机生成，包含山脉、海洋、森林、沙漠和河流——完全可根据你的喜好自定义。",
    "generateBtn": "⚔ 生成新地图",
    "downloadBtn": "⬇ 保存为PNG",
    "toggleSettingsBtn": "⚙ 设置",
    "lblSeed": "种子：",
    "grpCastles": "城堡",
    "lblMainCastle": "主城堡",
    "lblOutposts": "前哨",
    "lblNoOutposts": "无前哨",
    "grpTerrain": "地形",
    "lblMountains": "山脉",
    "lblSea": "海洋",
    "lblForest": "森林",
    "lblDesert": "沙漠",
    "grpRiver": "河流",
    "lblGenerateRiver": "生成河流",
    "lblBridges": "桥梁",
    "grpMap": "地图",
    "lblFields": "地块（100–10000）",
    "grpMarkers": "标记",
    "lblActionFields": "事件地块（每500个）",
    "lblMerchant": "商人地块编号",
    "footer": "每张地图都是随机重新生成的——地形、道路和前哨位置会略有不同。",
    "mapWord": "地图",
    "fieldsWord": "地块",
    "pngError": "PNG导出失败。可以尝试：右键点击地图 →\"图片另存为\"。",
    "options": {
      "aus": "关闭",
      "mitte": "中间",
      "oben": "上方",
      "unten": "下方",
      "links": "左侧",
      "rechts": "右侧",
      "oben-links": "左上",
      "oben-rechts": "右上",
      "unten-links": "左下",
      "unten-rechts": "右下"
    },
    "dir": "ltr",
    "pageTitle": "地图工坊",
    "heading": "D&D Helper",
    "indexSubtitle": "你的旅程从一张地图开始",
    "indexFooter": "地图工坊",
    "description": "创造属于你自己的奇幻世界——包含山脉、森林、河流与聚落。每张地图都是独一无二、可复现的，随时准备好迎接你的下一场冒险。",
    "buttonText": "查看地图"
  }
};
