/*
 * languages.js — gemeinsame Übersetzungsbibliothek für die Kartenwerkstatt.
 * Wird sowohl von MAP.html (Kartengenerator) als auch von index.html (Startseite) genutzt.
 *
 * Schlüssel für MAP.html: title, subtitle, generateBtn, downloadBtn, toggleSettingsBtn,
 *   copySettingsBtn, shareToggleBtn, mapWord, fieldsWord, pngError, options{...}
 * Schlüssel für index.html: dir, pageTitle, heading, indexSubtitle, description,
 *   buttonText, footer
 * ("subtitle" gehört zu MAP.html, "indexSubtitle" zur Startseite — bewusst getrennt,
 *  da beide Seiten unterschiedliche Untertitel-Texte brauchen.)
 *
 * Neue Sprache hinzufügen: einen neuen Eintrag mit all diesen Feldern ergänzen.
 */
const LANGUAGES = {
  "ar": {
    "nativeName": "العربية",
    "dir": "rtl",
    "title": "خريطة المملكة",
    "subtitle": "خريطة خيالية مرسومة يدويًا: تُنشأ عشوائيًا، مع جبال وبحر وغابة وصحراء ونهر – قابلة للتخصيص بالكامل حسب رغبتك.",
    "generateBtn": "⚔ إنشاء خريطة جديدة",
    "downloadBtn": "⬇ حفظ كصورة PNG",
    "toggleSettingsBtn": "⚙ الإعدادات",
    "mapWord": "خريطة",
    "fieldsWord": "حقول",
    "pngError": "فشل تصدير PNG. بدلاً من ذلك: انقر بزر الماوس الأيمن على الخريطة ← \"حفظ الصورة باسم\".",
    "options": {
      "aus": "إيقاف",
      "mitte": "المنتصف",
      "oben": "أعلى",
      "unten": "أسفل",
      "links": "يسار",
      "rechts": "يمين",
      "oben-links": "أعلى يسار",
      "oben-rechts": "أعلى يمين",
      "unten-links": "أسفل يسار",
      "unten-rechts": "أسفل يمين"
    },
    "pageTitle": "ورشة الخرائط",
    "heading": "D&D Helper",
    "indexSubtitle": "رحلتك تبدأ بخريطة",
    "description": "اصنع عالمك الخيالي الخاص — بجبال وغابات وأنهار ومستوطنات. كل خريطة فريدة وقابلة لإعادة الإنتاج وجاهزة لمغامرتك القادمة.",
    "buttonText": "إلى الخريطة",
    "footer": "ورشة الخرائط"
  },
  "bg": {
    "nativeName": "Български",
    "dir": "ltr",
    "title": "Карта на кралството",
    "subtitle": "Ръчно нарисувана фентъзи карта: генерирана на случаен принцип, с планини, море, гора, пустиня и река – напълно персонализируема по ваш вкус.",
    "generateBtn": "⚔ Генерирай нова карта",
    "downloadBtn": "⬇ Запази като PNG",
    "toggleSettingsBtn": "⚙ Настройки",
    "mapWord": "Карта",
    "fieldsWord": "полета",
    "pngError": "Експортът в PNG не бе успешен. Алтернативно: щракнете с десен бутон върху картата → \"Запази изображението като\".",
    "options": {
      "aus": "Изключено",
      "mitte": "Център",
      "oben": "Горе",
      "unten": "Долу",
      "links": "Ляво",
      "rechts": "Дясно",
      "oben-links": "Горе ляво",
      "oben-rechts": "Горе дясно",
      "unten-links": "Долу ляво",
      "unten-rechts": "Долу дясно"
    },
    "pageTitle": "Работилница за Карти",
    "heading": "D&D Helper",
    "indexSubtitle": "Пътуването ти започва с карта",
    "description": "Създай своя собствен фентъзи свят — с планини, гори, реки и селища. Всяка карта е уникална, възпроизводима и готова за следващото ти приключение.",
    "buttonText": "Към Картата",
    "footer": "Работилница за Карти"
  },
  "bn": {
    "nativeName": "বাংলা",
    "dir": "ltr",
    "title": "রাজ্যের মানচিত্র",
    "subtitle": "হাতে আঁকা একটি কল্পনার মানচিত্র: এলোমেলোভাবে তৈরি, পাহাড়, সমুদ্র, বন, মরুভূমি এবং একটি নদী সহ – সম্পূর্ণভাবে আপনার পছন্দমতো কাস্টমাইজযোগ্য।",
    "generateBtn": "⚔ নতুন মানচিত্র তৈরি করুন",
    "downloadBtn": "⬇ PNG হিসাবে সংরক্ষণ করুন",
    "toggleSettingsBtn": "⚙ সেটিংস",
    "mapWord": "মানচিত্র",
    "fieldsWord": "মাঠ",
    "pngError": "PNG এক্সপোর্ট ব্যর্থ হয়েছে। বিকল্পভাবে: মানচিত্রে ডান-ক্লিক করুন → \"চিত্র সংরক্ষণ করুন\"।",
    "options": {
      "aus": "বন্ধ",
      "mitte": "কেন্দ্র",
      "oben": "উপরে",
      "unten": "নিচে",
      "links": "বামে",
      "rechts": "ডানে",
      "oben-links": "উপরে বামে",
      "oben-rechts": "উপরে ডানে",
      "unten-links": "নিচে বামে",
      "unten-rechts": "নিচে ডানে"
    },
    "pageTitle": "মানচিত্র কর্মশালা",
    "heading": "D&D Helper",
    "indexSubtitle": "তোমার যাত্রা শুরু হয় একটি মানচিত্র দিয়ে",
    "description": "পাহাড়, বন, নদী এবং জনবসতি নিয়ে তৈরি করো তোমার নিজস্ব কল্পনার জগৎ। প্রতিটি মানচিত্র অনন্য, পুনরুৎপাদনযোগ্য এবং তোমার পরবর্তী অভিযানের জন্য প্রস্তুত।",
    "buttonText": "মানচিত্রে যান",
    "footer": "মানচিত্র কর্মশালা"
  },
  "ca": {
    "nativeName": "Català",
    "dir": "ltr",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "pageTitle": "Taller de Mapes",
    "heading": "D&D Helper",
    "indexSubtitle": "El teu viatge comença amb un mapa",
    "description": "Crea el teu propi món de fantasia — amb muntanyes, boscos, rius i assentaments. Cada mapa és únic, reproduïble i preparat per a la teva propera aventura.",
    "buttonText": "Anar al Mapa",
    "footer": "Taller de Mapes"
  },
  "cs": {
    "nativeName": "Čeština",
    "dir": "ltr",
    "title": "Mapa království",
    "subtitle": "Ručně kreslená fantasy mapa: náhodně generovaná, s horami, mořem, lesem, pouští a řekou – zcela přizpůsobitelná podle vašich přání.",
    "generateBtn": "⚔ Vygenerovat novou mapu",
    "downloadBtn": "⬇ Uložit jako PNG",
    "toggleSettingsBtn": "⚙ Nastavení",
    "mapWord": "Mapa",
    "fieldsWord": "polí",
    "pngError": "Export do PNG selhal. Alternativně: klikněte pravým tlačítkem na mapu → \"Uložit obrázek jako\".",
    "options": {
      "aus": "Vypnuto",
      "mitte": "Střed",
      "oben": "Nahoře",
      "unten": "Dole",
      "links": "Vlevo",
      "rechts": "Vpravo",
      "oben-links": "Nahoře vlevo",
      "oben-rechts": "Nahoře vpravo",
      "unten-links": "Dole vlevo",
      "unten-rechts": "Dole vpravo"
    },
    "pageTitle": "Dílna Map",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvá cesta začíná mapou",
    "description": "Vytvoř si vlastní fantasy svět — s horami, lesy, řekami a osadami. Každá mapa je jedinečná, reprodukovatelná a připravená na tvé další dobrodružství.",
    "buttonText": "K Mapě",
    "footer": "Dílna Map"
  },
  "da": {
    "nativeName": "Dansk",
    "dir": "ltr",
    "title": "Kongerigets kort",
    "subtitle": "Et håndtegnet fantasikort: genereret tilfældigt, med bjerge, hav, skov, ørken og en flod – fuldt tilpasseligt efter dine ønsker.",
    "generateBtn": "⚔ Generer nyt kort",
    "downloadBtn": "⬇ Gem som PNG",
    "toggleSettingsBtn": "⚙ Indstillinger",
    "mapWord": "Kort",
    "fieldsWord": "felter",
    "pngError": "PNG-eksport mislykkedes. Alternativt: højreklik på kortet → \"Gem billede som\".",
    "options": {
      "aus": "Fra",
      "mitte": "Midte",
      "oben": "Top",
      "unten": "Bund",
      "links": "Venstre",
      "rechts": "Højre",
      "oben-links": "Top venstre",
      "oben-rechts": "Top højre",
      "unten-links": "Bund venstre",
      "unten-rechts": "Bund højre"
    },
    "pageTitle": "Kortværksted",
    "heading": "D&D Helper",
    "indexSubtitle": "Din rejse begynder med et kort",
    "description": "Skab din egen fantasiverden — med bjerge, skove, floder og bosættelser. Hvert kort er unikt, reproducerbart og klar til dit næste eventyr.",
    "buttonText": "Til Kortet",
    "footer": "Kortværksted"
  },
  "de": {
    "nativeName": "Deutsch",
    "dir": "ltr",
    "title": "Karte des Königreichs",
    "subtitle": "Eine handgezeichnete Fantasiekarte: zufällig generiert, mit Bergen, Meer, Wald, Wüste und Fluss – und komplett nach deinen Wünschen einstellbar.",
    "generateBtn": "⚔ Neue Karte erzeugen",
    "downloadBtn": "⬇ Als PNG speichern",
    "toggleSettingsBtn": "⚙ Einstellungen",
    "copySettingsBtn": "📋 Kopieren",
    "shareToggleBtn": "🔗 Teilen",
    "mapWord": "Karte",
    "fieldsWord": "Felder",
    "pngError": "PNG-Export ist fehlgeschlagen. Alternativ: Rechtsklick auf die Karte → \"Grafik speichern unter\".",
    "options": {
      "aus": "Aus",
      "mitte": "Mitte",
      "oben": "Oben",
      "unten": "Unten",
      "links": "Links",
      "rechts": "Rechts",
      "oben-links": "Oben links",
      "oben-rechts": "Oben rechts",
      "unten-links": "Unten links",
      "unten-rechts": "Unten rechts"
    },
    "pageTitle": "Kartenwerkstatt",
    "heading": "D&D Helper",
    "indexSubtitle": "Deine Reise beginnt mit einer Karte",
    "description": "Erschaffe deine eigene Fantasiewelt — mit Bergen, Wäldern, Flüssen und Siedlungen. Jede Karte ist einzigartig, reproduzierbar und bereit für dein nächstes Abenteuer.",
    "buttonText": "Zur Karte",
    "footer": "Kartenwerkstatt"
  },
  "el": {
    "nativeName": "Ελληνικά",
    "dir": "ltr",
    "title": "Χάρτης του Βασιλείου",
    "subtitle": "Ένας χειροποίητος φανταστικός χάρτης: δημιουργείται τυχαία, με βουνά, θάλασσα, δάσος, έρημο και ποτάμι – πλήρως προσαρμόσιμος στις επιθυμίες σας.",
    "generateBtn": "⚔ Δημιουργία νέου χάρτη",
    "downloadBtn": "⬇ Αποθήκευση ως PNG",
    "toggleSettingsBtn": "⚙ Ρυθμίσεις",
    "mapWord": "Χάρτης",
    "fieldsWord": "πεδία",
    "pngError": "Η εξαγωγή PNG απέτυχε. Εναλλακτικά: δεξί κλικ στον χάρτη → \"Αποθήκευση εικόνας ως\".",
    "options": {
      "aus": "Απενεργοποιημένο",
      "mitte": "Κέντρο",
      "oben": "Πάνω",
      "unten": "Κάτω",
      "links": "Αριστερά",
      "rechts": "Δεξιά",
      "oben-links": "Πάνω αριστερά",
      "oben-rechts": "Πάνω δεξιά",
      "unten-links": "Κάτω αριστερά",
      "unten-rechts": "Κάτω δεξιά"
    },
    "pageTitle": "Εργαστήρι Χαρτών",
    "heading": "D&D Helper",
    "indexSubtitle": "Το ταξίδι σου ξεκινά με έναν χάρτη",
    "description": "Δημιούργησε τον δικό σου φανταστικό κόσμο — με βουνά, δάση, ποτάμια και οικισμούς. Κάθε χάρτης είναι μοναδικός, αναπαραγώγιμος και έτοιμος για την επόμενή σου περιπέτεια.",
    "buttonText": "Στον Χάρτη",
    "footer": "Εργαστήρι Χαρτών"
  },
  "en": {
    "nativeName": "English",
    "dir": "ltr",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map",
    "footer": "Map Workshop"
  },
  "es": {
    "nativeName": "Español",
    "dir": "ltr",
    "title": "Mapa del Reino",
    "subtitle": "Un mapa de fantasía dibujado a mano: generado aleatoriamente, con montañas, mar, bosque, desierto y un río – totalmente personalizable a tu gusto.",
    "generateBtn": "⚔ Generar nuevo mapa",
    "downloadBtn": "⬇ Guardar como PNG",
    "toggleSettingsBtn": "⚙ Ajustes",
    "mapWord": "Mapa",
    "fieldsWord": "casillas",
    "pngError": "La exportación a PNG ha fallado. Alternativa: clic derecho en el mapa → \"Guardar imagen como\".",
    "options": {
      "aus": "Desactivado",
      "mitte": "Centro",
      "oben": "Arriba",
      "unten": "Abajo",
      "links": "Izquierda",
      "rechts": "Derecha",
      "oben-links": "Arriba izquierda",
      "oben-rechts": "Arriba derecha",
      "unten-links": "Abajo izquierda",
      "unten-rechts": "Abajo derecha"
    },
    "pageTitle": "Taller de Mapas",
    "heading": "D&D Helper",
    "indexSubtitle": "Tu viaje comienza con un mapa",
    "description": "Crea tu propio mundo de fantasía, con montañas, bosques, ríos y asentamientos. Cada mapa es único, reproducible y listo para tu próxima aventura.",
    "buttonText": "Ir al Mapa",
    "footer": "Taller de Mapas"
  },
  "et": {
    "nativeName": "Eesti",
    "dir": "ltr",
    "title": "Kuningriigi kaart",
    "subtitle": "Käsitsi joonistatud fantaasiakaart: genereeritud juhuslikult, mägede, mere, metsa, kõrbe ja jõega – täielikult sinu soovi järgi kohandatav.",
    "generateBtn": "⚔ Loo uus kaart",
    "downloadBtn": "⬇ Salvesta PNG-na",
    "toggleSettingsBtn": "⚙ Seaded",
    "mapWord": "Kaart",
    "fieldsWord": "välja",
    "pngError": "PNG eksportimine ebaõnnestus. Alternatiivina: paremklõps kaardil → \"Salvesta pilt nimega\".",
    "options": {
      "aus": "Väljas",
      "mitte": "Keskel",
      "oben": "Üleval",
      "unten": "All",
      "links": "Vasakul",
      "rechts": "Paremal",
      "oben-links": "Üleval vasakul",
      "oben-rechts": "Üleval paremal",
      "unten-links": "All vasakul",
      "unten-rechts": "All paremal"
    },
    "pageTitle": "Kaartide Töökoda",
    "heading": "D&D Helper",
    "indexSubtitle": "Sinu teekond algab kaardiga",
    "description": "Loo oma fantaasiamaailm — mägede, metsade, jõgede ja asulatega. Iga kaart on unikaalne, korratav ja valmis sinu järgmiseks seikluseks.",
    "buttonText": "Kaardile",
    "footer": "Kaartide Töökoda"
  },
  "eu": {
    "nativeName": "Euskara",
    "dir": "ltr",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "pageTitle": "Mapa-tailerra",
    "heading": "D&D Helper",
    "indexSubtitle": "Zure bidaia mapa batekin hasten da",
    "description": "Sortu zeure fantasiazko mundua — mendiak, basoak, ibaiak eta herriguneak dituena. Mapa bakoitza bakarra, erreproduzigarria eta zure hurrengo abenturarako prest dago.",
    "buttonText": "Mapara Joan",
    "footer": "Mapa-tailerra"
  },
  "fa": {
    "nativeName": "فارسی",
    "dir": "rtl",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "pageTitle": "کارگاه نقشه",
    "heading": "D&D Helper",
    "indexSubtitle": "سفر تو با یک نقشه آغاز می‌شود",
    "description": "دنیای خیالی خودت را بساز — با کوه‌ها، جنگل‌ها، رودخانه‌ها و سکونتگاه‌ها. هر نقشه منحصربه‌فرد، قابل بازتولید و آماده ماجراجویی بعدی توست.",
    "buttonText": "برو به نقشه",
    "footer": "کارگاه نقشه"
  },
  "fi": {
    "nativeName": "Suomi",
    "dir": "ltr",
    "title": "Kuningaskunnan kartta",
    "subtitle": "Käsin piirretty fantasiakartta: satunnaisesti luotu, vuorineen, merineen, metsineen, aavikkoineen ja jokineen – täysin muokattavissa mieltymystesi mukaan.",
    "generateBtn": "⚔ Luo uusi kartta",
    "downloadBtn": "⬇ Tallenna PNG:nä",
    "toggleSettingsBtn": "⚙ Asetukset",
    "mapWord": "Kartta",
    "fieldsWord": "ruutua",
    "pngError": "PNG-vienti epäonnistui. Vaihtoehtoisesti: napsauta karttaa hiiren oikealla painikkeella → \"Tallenna kuva nimellä\".",
    "options": {
      "aus": "Pois",
      "mitte": "Keskellä",
      "oben": "Ylhäällä",
      "unten": "Alhaalla",
      "links": "Vasemmalla",
      "rechts": "Oikealla",
      "oben-links": "Ylhäällä vasemmalla",
      "oben-rechts": "Ylhäällä oikealla",
      "unten-links": "Alhaalla vasemmalla",
      "unten-rechts": "Alhaalla oikealla"
    },
    "pageTitle": "Karttapaja",
    "heading": "D&D Helper",
    "indexSubtitle": "Matkasi alkaa kartasta",
    "description": "Luo oma fantasiamaailmasi — vuorineen, metsineen, jokineen ja asutuksineen. Jokainen kartta on ainutlaatuinen, toistettavissa ja valmis seuraavaan seikkailuusi.",
    "buttonText": "Kartalle",
    "footer": "Karttapaja"
  },
  "fr": {
    "nativeName": "Français",
    "dir": "ltr",
    "title": "Carte du Royaume",
    "subtitle": "Une carte de fantasy dessinée à la main : générée aléatoirement, avec montagnes, mer, forêt, désert et une rivière – entièrement personnalisable selon vos envies.",
    "generateBtn": "⚔ Générer une nouvelle carte",
    "downloadBtn": "⬇ Enregistrer en PNG",
    "toggleSettingsBtn": "⚙ Paramètres",
    "mapWord": "Carte",
    "fieldsWord": "cases",
    "pngError": "L'export PNG a échoué. Alternative : clic droit sur la carte → \"Enregistrer l'image sous\".",
    "options": {
      "aus": "Désactivé",
      "mitte": "Centre",
      "oben": "Haut",
      "unten": "Bas",
      "links": "Gauche",
      "rechts": "Droite",
      "oben-links": "Haut gauche",
      "oben-rechts": "Haut droite",
      "unten-links": "Bas gauche",
      "unten-rechts": "Bas droite"
    },
    "pageTitle": "Atelier de Cartes",
    "heading": "D&D Helper",
    "indexSubtitle": "Ton voyage commence avec une carte",
    "description": "Crée ton propre monde fantastique — avec des montagnes, des forêts, des rivières et des colonies. Chaque carte est unique, reproductible et prête pour ta prochaine aventure.",
    "buttonText": "Voir la Carte",
    "footer": "Atelier de Cartes"
  },
  "ga": {
    "nativeName": "Gaeilge",
    "dir": "ltr",
    "title": "Léarscáil na Ríochta",
    "subtitle": "Léarscáil fantaisíochta lámhtharraingthe: gineadh go randamach, le sléibhte, farraige, foraois, fásach agus abhainn – inoiriúnaithe go hiomlán de réir do mhian.",
    "generateBtn": "⚔ Gin Léarscáil Nua",
    "downloadBtn": "⬇ Sábháil mar PNG",
    "toggleSettingsBtn": "⚙ Socruithe",
    "mapWord": "Léarscáil",
    "fieldsWord": "páirceanna",
    "pngError": "Theip ar onnmhairiú PNG. Mar rogha eile: deaschliceáil ar an léarscáil → \"Sábháil an íomhá mar\".",
    "options": {
      "aus": "As",
      "mitte": "Lár",
      "oben": "Barr",
      "unten": "Bun",
      "links": "Clé",
      "rechts": "Deas",
      "oben-links": "Barr clé",
      "oben-rechts": "Barr deas",
      "unten-links": "Bun clé",
      "unten-rechts": "Bun deas"
    },
    "pageTitle": "Ceardlann Léarscáileanna",
    "heading": "D&D Helper",
    "indexSubtitle": "Tosaíonn do thuras le léarscáil",
    "description": "Cruthaigh do shaol fantaisíochta féin — le sléibhte, foraoisí, aibhneacha agus lonnaíochtaí. Tá gach léarscáil uathúil, in-atáirgthe agus réidh do d'eachtra eile.",
    "buttonText": "Chuig an Léarscáil",
    "footer": "Ceardlann Léarscáileanna"
  },
  "hi": {
    "nativeName": "हिन्दी",
    "dir": "ltr",
    "title": "राज्य का नक्शा",
    "subtitle": "हाथ से बना काल्पनिक नक्शा: यादृच्छिक रूप से बनाया गया, पहाड़ों, समुद्र, जंगल, रेगिस्तान और एक नदी के साथ – पूरी तरह से आपकी पसंद के अनुसार अनुकूलन योग्य।",
    "generateBtn": "⚔ नया नक्शा बनाएं",
    "downloadBtn": "⬇ PNG के रूप में सहेजें",
    "toggleSettingsBtn": "⚙ सेटिंग्स",
    "mapWord": "नक्शा",
    "fieldsWord": "खेत",
    "pngError": "PNG निर्यात विफल रहा। वैकल्पिक रूप से: नक्शे पर राइट-क्लिक करें → \"छवि को इस रूप में सहेजें\"।",
    "options": {
      "aus": "बंद",
      "mitte": "केंद्र",
      "oben": "ऊपर",
      "unten": "नीचे",
      "links": "बाएं",
      "rechts": "दाएं",
      "oben-links": "ऊपर बाएं",
      "oben-rechts": "ऊपर दाएं",
      "unten-links": "नीचे बाएं",
      "unten-rechts": "नीचे दाएं"
    },
    "pageTitle": "मानचित्र कार्यशाला",
    "heading": "D&D Helper",
    "indexSubtitle": "आपकी यात्रा एक मानचित्र से शुरू होती है",
    "description": "पहाड़ों, जंगलों, नदियों और बस्तियों के साथ अपनी खुद की काल्पनिक दुनिया बनाएं। हर मानचित्र अनोखा, पुनरुत्पादनीय और आपके अगले रोमांच के लिए तैयार है।",
    "buttonText": "मानचित्र पर जाएं",
    "footer": "मानचित्र कार्यशाला"
  },
  "hr": {
    "nativeName": "Hrvatski",
    "dir": "ltr",
    "title": "Karta kraljevstva",
    "subtitle": "Ručno crtana fantastična karta: generirana nasumično, s planinama, morem, šumom, pustinjom i rijekom – potpuno prilagodljiva vašim željama.",
    "generateBtn": "⚔ Generiraj novu kartu",
    "downloadBtn": "⬇ Spremi kao PNG",
    "toggleSettingsBtn": "⚙ Postavke",
    "mapWord": "Karta",
    "fieldsWord": "polja",
    "pngError": "Izvoz u PNG nije uspio. Alternativno: desni klik na kartu → \"Spremi sliku kao\".",
    "options": {
      "aus": "Isključeno",
      "mitte": "Sredina",
      "oben": "Gore",
      "unten": "Dolje",
      "links": "Lijevo",
      "rechts": "Desno",
      "oben-links": "Gore lijevo",
      "oben-rechts": "Gore desno",
      "unten-links": "Dolje lijevo",
      "unten-rechts": "Dolje desno"
    },
    "pageTitle": "Radionica Karata",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoje putovanje počinje kartom",
    "description": "Stvori svoj vlastiti fantastični svijet — s planinama, šumama, rijekama i naseljima. Svaka karta je jedinstvena, reproducibilna i spremna za tvoju sljedeću pustolovinu.",
    "buttonText": "Na Kartu",
    "footer": "Radionica Karata"
  },
  "hu": {
    "nativeName": "Magyar",
    "dir": "ltr",
    "title": "A Királyság térképe",
    "subtitle": "Kézzel rajzolt fantasy térkép: véletlenszerűen generált, hegyekkel, tengerrel, erdővel, sivataggal és folyóval – teljesen az igényeid szerint testreszabható.",
    "generateBtn": "⚔ Új térkép generálása",
    "downloadBtn": "⬇ Mentés PNG-ként",
    "toggleSettingsBtn": "⚙ Beállítások",
    "mapWord": "Térkép",
    "fieldsWord": "mező",
    "pngError": "A PNG exportálása sikertelen volt. Alternatíva: jobb kattintás a térképre → \"Kép mentése másként\".",
    "options": {
      "aus": "Ki",
      "mitte": "Közép",
      "oben": "Fent",
      "unten": "Lent",
      "links": "Bal",
      "rechts": "Jobb",
      "oben-links": "Fent balra",
      "oben-rechts": "Fent jobbra",
      "unten-links": "Lent balra",
      "unten-rechts": "Lent jobbra"
    },
    "pageTitle": "Térképműhely",
    "heading": "D&D Helper",
    "indexSubtitle": "Utazásod egy térképpel kezdődik",
    "description": "Alkosd meg saját fantasyvilágodat — hegyekkel, erdőkkel, folyókkal és településekkel. Minden térkép egyedi, reprodukálható és készen áll a következő kalandodra.",
    "buttonText": "A Térképhez",
    "footer": "Térképműhely"
  },
  "id": {
    "nativeName": "Bahasa Indonesia",
    "dir": "ltr",
    "title": "Peta Kerajaan",
    "subtitle": "Peta fantasi gambar tangan: dibuat secara acak, dengan gunung, laut, hutan, gurun, dan sungai – sepenuhnya dapat disesuaikan sesuai keinginan Anda.",
    "generateBtn": "⚔ Buat Peta Baru",
    "downloadBtn": "⬇ Simpan sebagai PNG",
    "toggleSettingsBtn": "⚙ Pengaturan",
    "mapWord": "Peta",
    "fieldsWord": "petak",
    "pngError": "Ekspor PNG gagal. Alternatif: klik kanan pada peta → \"Simpan gambar sebagai\".",
    "options": {
      "aus": "Mati",
      "mitte": "Tengah",
      "oben": "Atas",
      "unten": "Bawah",
      "links": "Kiri",
      "rechts": "Kanan",
      "oben-links": "Atas kiri",
      "oben-rechts": "Atas kanan",
      "unten-links": "Bawah kiri",
      "unten-rechts": "Bawah kanan"
    },
    "pageTitle": "Bengkel Peta",
    "heading": "D&D Helper",
    "indexSubtitle": "Perjalananmu dimulai dengan sebuah peta",
    "description": "Ciptakan duniamu sendiri yang penuh fantasi — dengan gunung, hutan, sungai, dan pemukiman. Setiap peta unik, dapat direproduksi, dan siap untuk petualangan berikutnya.",
    "buttonText": "Ke Peta",
    "footer": "Bengkel Peta"
  },
  "is": {
    "nativeName": "Íslenska",
    "dir": "ltr",
    "title": "Kort konungsríkisins",
    "subtitle": "Handteiknað ævintýrakort: búið til af handahófi, með fjöllum, hafi, skógi, eyðimörk og á – fullkomlega sérsniðið að þínum óskum.",
    "generateBtn": "⚔ Búa til nýtt kort",
    "downloadBtn": "⬇ Vista sem PNG",
    "toggleSettingsBtn": "⚙ Stillingar",
    "mapWord": "Kort",
    "fieldsWord": "reitir",
    "pngError": "PNG-útflutningur mistókst. Að öðrum kosti: hægrismelltu á kortið → \"Vista mynd sem\".",
    "options": {
      "aus": "Slökkt",
      "mitte": "Miðja",
      "oben": "Efst",
      "unten": "Neðst",
      "links": "Vinstri",
      "rechts": "Hægri",
      "oben-links": "Efst vinstri",
      "oben-rechts": "Efst hægri",
      "unten-links": "Neðst vinstri",
      "unten-rechts": "Neðst hægri"
    },
    "pageTitle": "Kortasmiðja",
    "heading": "D&D Helper",
    "indexSubtitle": "Ferðalag þitt hefst með korti",
    "description": "Skapaðu þinn eigin ævintýraheim — með fjöllum, skógum, ám og byggðum. Hvert kort er einstakt, endurskapanlegt og tilbúið fyrir næsta ævintýri þitt.",
    "buttonText": "Á Kortið",
    "footer": "Kortasmiðja"
  },
  "it": {
    "nativeName": "Italiano",
    "dir": "ltr",
    "title": "Mappa del Regno",
    "subtitle": "Una mappa fantasy disegnata a mano: generata casualmente, con montagne, mare, foresta, deserto e un fiume – completamente personalizzabile a piacimento.",
    "generateBtn": "⚔ Genera nuova mappa",
    "downloadBtn": "⬇ Salva come PNG",
    "toggleSettingsBtn": "⚙ Impostazioni",
    "mapWord": "Mappa",
    "fieldsWord": "caselle",
    "pngError": "Esportazione PNG non riuscita. In alternativa: clic destro sulla mappa → \"Salva immagine con nome\".",
    "options": {
      "aus": "Disattivato",
      "mitte": "Centro",
      "oben": "Sopra",
      "unten": "Sotto",
      "links": "Sinistra",
      "rechts": "Destra",
      "oben-links": "Sopra sinistra",
      "oben-rechts": "Sopra destra",
      "unten-links": "Sotto sinistra",
      "unten-rechts": "Sotto destra"
    },
    "pageTitle": "Bottega delle Mappe",
    "heading": "D&D Helper",
    "indexSubtitle": "Il tuo viaggio inizia con una mappa",
    "description": "Crea il tuo mondo fantastico — con montagne, foreste, fiumi e insediamenti. Ogni mappa è unica, riproducibile e pronta per la tua prossima avventura.",
    "buttonText": "Vai alla Mappa",
    "footer": "Bottega delle Mappe"
  },
  "ja": {
    "nativeName": "日本語",
    "dir": "ltr",
    "title": "王国の地図",
    "subtitle": "手描きのファンタジーマップ：ランダムに生成され、山、海、森、砂漠、川があり、お好みに合わせて完全にカスタマイズ可能です。",
    "generateBtn": "⚔ 新しい地図を生成",
    "downloadBtn": "⬇ PNGとして保存",
    "toggleSettingsBtn": "⚙ 設定",
    "mapWord": "地図",
    "fieldsWord": "マス",
    "pngError": "PNGのエクスポートに失敗しました。代わりに地図を右クリック →「名前を付けて画像を保存」をお試しください。",
    "options": {
      "aus": "オフ",
      "mitte": "中央",
      "oben": "上",
      "unten": "下",
      "links": "左",
      "rechts": "右",
      "oben-links": "左上",
      "oben-rechts": "右上",
      "unten-links": "左下",
      "unten-rechts": "右下"
    },
    "pageTitle": "地図工房",
    "heading": "D&D Helper",
    "indexSubtitle": "あなたの旅は一枚の地図から始まる",
    "description": "山、森、川、集落を備えた、あなただけのファンタジー世界を創り出そう。すべての地図は唯一無二でありながら再現可能。次の冒険への準備は整っている。",
    "buttonText": "地図を見る",
    "footer": "地図工房"
  },
  "ko": {
    "nativeName": "한국어",
    "dir": "ltr",
    "title": "왕국 지도",
    "subtitle": "손으로 그린 판타지 지도: 무작위로 생성되며 산, 바다, 숲, 사막, 강이 있고 원하는 대로 완전히 사용자 지정할 수 있습니다.",
    "generateBtn": "⚔ 새 지도 생성",
    "downloadBtn": "⬇ PNG로 저장",
    "toggleSettingsBtn": "⚙ 설정",
    "mapWord": "지도",
    "fieldsWord": "칸",
    "pngError": "PNG 내보내기에 실패했습니다. 대신: 지도를 마우스 오른쪽 버튼으로 클릭 → \"이미지를 다른 이름으로 저장\"을 시도하세요.",
    "options": {
      "aus": "꺼짐",
      "mitte": "중앙",
      "oben": "위",
      "unten": "아래",
      "links": "왼쪽",
      "rechts": "오른쪽",
      "oben-links": "왼쪽 위",
      "oben-rechts": "오른쪽 위",
      "unten-links": "왼쪽 아래",
      "unten-rechts": "오른쪽 아래"
    },
    "pageTitle": "지도 공방",
    "heading": "D&D Helper",
    "indexSubtitle": "당신의 여정은 지도 한 장에서 시작됩니다",
    "description": "산, 숲, 강, 정착지가 있는 나만의 판타지 세계를 만들어보세요. 모든 지도는 고유하며 재현 가능하고, 다음 모험을 위한 준비가 되어 있습니다.",
    "buttonText": "지도로 이동",
    "footer": "지도 공방"
  },
  "lt": {
    "nativeName": "Lietuvių",
    "dir": "ltr",
    "title": "Karalystės žemėlapis",
    "subtitle": "Ranka piešti fantastinis žemėlapis: sugeneruotas atsitiktinai, su kalnais, jūra, mišku, dykuma ir upe – visiškai pritaikomas pagal jūsų norus.",
    "generateBtn": "⚔ Generuoti naują žemėlapį",
    "downloadBtn": "⬇ Išsaugoti kaip PNG",
    "toggleSettingsBtn": "⚙ Nustatymai",
    "mapWord": "Žemėlapis",
    "fieldsWord": "laukai",
    "pngError": "PNG eksportavimas nepavyko. Alternatyviai: spustelėkite dešiniuoju pelės mygtuku ant žemėlapio → \"Išsaugoti paveikslėlį kaip\".",
    "options": {
      "aus": "Išjungta",
      "mitte": "Centras",
      "oben": "Viršuje",
      "unten": "Apačioje",
      "links": "Kairėje",
      "rechts": "Dešinėje",
      "oben-links": "Viršuje kairėje",
      "oben-rechts": "Viršuje dešinėje",
      "unten-links": "Apačioje kairėje",
      "unten-rechts": "Apačioje dešinėje"
    },
    "pageTitle": "Žemėlapių Dirbtuvė",
    "heading": "D&D Helper",
    "indexSubtitle": "Tavo kelionė prasideda nuo žemėlapio",
    "description": "Sukurk savo fantastinį pasaulį — su kalnais, miškais, upėmis ir gyvenvietėmis. Kiekvienas žemėlapis yra unikalus, atkuriamas ir paruoštas tavo kitam nuotykiui.",
    "buttonText": "Į Žemėlapį",
    "footer": "Žemėlapių Dirbtuvė"
  },
  "lv": {
    "nativeName": "Latviešu",
    "dir": "ltr",
    "title": "Karalistes karte",
    "subtitle": "Ar roku zīmēta fantāzijas karte: izveidota nejauši, ar kalniem, jūru, mežu, tuksnesi un upi – pilnībā pielāgojama pēc jūsu vēlmēm.",
    "generateBtn": "⚔ Ģenerēt jaunu karti",
    "downloadBtn": "⬇ Saglabāt kā PNG",
    "toggleSettingsBtn": "⚙ Iestatījumi",
    "mapWord": "Karte",
    "fieldsWord": "lauki",
    "pngError": "PNG eksportēšana neizdevās. Alternatīvi: veiciet labo klikšķi uz kartes → \"Saglabāt attēlu kā\".",
    "options": {
      "aus": "Izslēgts",
      "mitte": "Centrs",
      "oben": "Augšā",
      "unten": "Apakšā",
      "links": "Kreisā",
      "rechts": "Labā",
      "oben-links": "Augšā kreisā",
      "oben-rechts": "Augšā labā",
      "unten-links": "Apakšā kreisā",
      "unten-rechts": "Apakšā labā"
    },
    "pageTitle": "Karšu Darbnīca",
    "heading": "D&D Helper",
    "indexSubtitle": "Tavs ceļojums sākas ar karti",
    "description": "Radi savu paša fantāzijas pasauli — ar kalniem, mežiem, upēm un apmetnēm. Katra karte ir unikāla, atkārtojama un gatava tavam nākamajam piedzīvojumam.",
    "buttonText": "Uz Karti",
    "footer": "Karšu Darbnīca"
  },
  "mr": {
    "nativeName": "मराठी",
    "dir": "ltr",
    "title": "राज्याचा नकाशा",
    "subtitle": "हाताने काढलेला काल्पनिक नकाशा: यादृच्छिकपणे तयार केलेला, डोंगर, समुद्र, जंगल, वाळवंट आणि नदीसह – पूर्णपणे आपल्या आवडीनुसार सानुकूल करण्यायोग्य.",
    "generateBtn": "⚔ नवीन नकाशा तयार करा",
    "downloadBtn": "⬇ PNG म्हणून जतन करा",
    "toggleSettingsBtn": "⚙ सेटिंग्ज",
    "mapWord": "नकाशा",
    "fieldsWord": "शेत",
    "pngError": "PNG निर्यात अयशस्वी झाले. पर्यायाने: नकाशावर उजवे-क्लिक करा → \"प्रतिमा जतन करा\".",
    "options": {
      "aus": "बंद",
      "mitte": "मध्यभागी",
      "oben": "वर",
      "unten": "खाली",
      "links": "डावीकडे",
      "rechts": "उजवीकडे",
      "oben-links": "वर डावीकडे",
      "oben-rechts": "वर उजवीकडे",
      "unten-links": "खाली डावीकडे",
      "unten-rechts": "खाली उजवीकडे"
    },
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map",
    "footer": "Map Workshop"
  },
  "mt": {
    "nativeName": "Malti",
    "dir": "ltr",
    "title": "Mappa tas-Saltna",
    "subtitle": "Mappa fantażjuża miktuba bl-idejn: iġġenerata b'mod każwali, b'muntanji, baħar, foresta, deżert u xmara – kompletament tista' tiġi kkustomizzata skont ix-xewqat tiegħek.",
    "generateBtn": "⚔ Iġġenera Mappa Ġdida",
    "downloadBtn": "⬇ Issejvja bħala PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "mapWord": "Mappa",
    "fieldsWord": "oqsma",
    "pngError": "L-esportazzjoni PNG falliet. Alternattivament: ikklikkja bil-lemin fuq il-mappa → \"Issejvja x-xbieha bħala\".",
    "options": {
      "aus": "Mitfi",
      "mitte": "Ċentru",
      "oben": "Fuq",
      "unten": "Isfel",
      "links": "Xellug",
      "rechts": "Lemin",
      "oben-links": "Fuq xellug",
      "oben-rechts": "Fuq lemin",
      "unten-links": "Isfel xellug",
      "unten-rechts": "Isfel lemin"
    },
    "pageTitle": "Ħanut tal-Mapep",
    "heading": "D&D Helper",
    "indexSubtitle": "Il-vjaġġ tiegħek jibda b'mappa",
    "description": "Ħoloq id-dinja fantastika tiegħek stess — b'muntanji, foresti, xmajjar u insedjamenti. Kull mappa hija unika, riproduċibbli u lesta għall-avventura li jmiss tiegħek.",
    "buttonText": "Mur għall-Mappa",
    "footer": "Ħanut tal-Mapep"
  },
  "nl": {
    "nativeName": "Nederlands",
    "dir": "ltr",
    "title": "Kaart van het Koninkrijk",
    "subtitle": "Een handgetekende fantasiekaart: willekeurig gegenereerd, met bergen, zee, bos, woestijn en een rivier – volledig aanpasbaar naar wens.",
    "generateBtn": "⚔ Nieuwe kaart genereren",
    "downloadBtn": "⬇ Opslaan als PNG",
    "toggleSettingsBtn": "⚙ Instellingen",
    "mapWord": "Kaart",
    "fieldsWord": "velden",
    "pngError": "PNG-export is mislukt. Alternatief: rechtsklik op de kaart → \"Afbeelding opslaan als\".",
    "options": {
      "aus": "Uit",
      "mitte": "Midden",
      "oben": "Boven",
      "unten": "Onder",
      "links": "Links",
      "rechts": "Rechts",
      "oben-links": "Boven links",
      "oben-rechts": "Boven rechts",
      "unten-links": "Onder links",
      "unten-rechts": "Onder rechts"
    },
    "pageTitle": "Kaartenwerkplaats",
    "heading": "D&D Helper",
    "indexSubtitle": "Jouw reis begint met een kaart",
    "description": "Creëer je eigen fantasiewereld — met bergen, bossen, rivieren en nederzettingen. Elke kaart is uniek, reproduceerbaar en klaar voor je volgende avontuur.",
    "buttonText": "Naar de Kaart",
    "footer": "Kaartenwerkplaats"
  },
  "no": {
    "nativeName": "Norsk",
    "dir": "ltr",
    "title": "Kongerikets kart",
    "subtitle": "Et håndtegnet fantasikart: tilfeldig generert, med fjell, hav, skog, ørken og en elv – fullt tilpassbart etter dine ønsker.",
    "generateBtn": "⚔ Generer nytt kart",
    "downloadBtn": "⬇ Lagre som PNG",
    "toggleSettingsBtn": "⚙ Innstillinger",
    "mapWord": "Kart",
    "fieldsWord": "felt",
    "pngError": "PNG-eksport mislyktes. Alternativt: høyreklikk på kartet → \"Lagre bilde som\".",
    "options": {
      "aus": "Av",
      "mitte": "Midten",
      "oben": "Topp",
      "unten": "Bunn",
      "links": "Venstre",
      "rechts": "Høyre",
      "oben-links": "Topp venstre",
      "oben-rechts": "Topp høyre",
      "unten-links": "Bunn venstre",
      "unten-rechts": "Bunn høyre"
    },
    "pageTitle": "Kartverksted",
    "heading": "D&D Helper",
    "indexSubtitle": "Reisen din begynner med et kart",
    "description": "Skap din egen fantasiverden — med fjell, skoger, elver og bosetninger. Hvert kart er unikt, reproduserbart og klart for ditt neste eventyr.",
    "buttonText": "Til Kartet",
    "footer": "Kartverksted"
  },
  "pl": {
    "nativeName": "Polski",
    "dir": "ltr",
    "title": "Mapa Królestwa",
    "subtitle": "Ręcznie rysowana mapa fantasy: generowana losowo, z górami, morzem, lasem, pustynią i rzeką – w pełni dostosowywana do Twoich upodobań.",
    "generateBtn": "⚔ Wygeneruj nową mapę",
    "downloadBtn": "⬇ Zapisz jako PNG",
    "toggleSettingsBtn": "⚙ Ustawienia",
    "mapWord": "Mapa",
    "fieldsWord": "pól",
    "pngError": "Eksport do PNG nie powiódł się. Alternatywnie: kliknij prawym przyciskiem myszy na mapie → \"Zapisz obraz jako\".",
    "options": {
      "aus": "Wyłączone",
      "mitte": "Środek",
      "oben": "Góra",
      "unten": "Dół",
      "links": "Lewo",
      "rechts": "Prawo",
      "oben-links": "Góra lewo",
      "oben-rechts": "Góra prawo",
      "unten-links": "Dół lewo",
      "unten-rechts": "Dół prawo"
    },
    "pageTitle": "Pracownia Map",
    "heading": "D&D Helper",
    "indexSubtitle": "Twoja podróż zaczyna się od mapy",
    "description": "Stwórz własny fantastyczny świat — z górami, lasami, rzekami i osadami. Każda mapa jest unikalna, odtwarzalna i gotowa na twoją kolejną przygodę.",
    "buttonText": "Przejdź do Mapy",
    "footer": "Pracownia Map"
  },
  "pt": {
    "nativeName": "Português",
    "dir": "ltr",
    "title": "Mapa do Reino",
    "subtitle": "Um mapa de fantasia desenhado à mão: gerado aleatoriamente, com montanhas, mar, floresta, deserto e um rio – totalmente personalizável ao seu gosto.",
    "generateBtn": "⚔ Gerar novo mapa",
    "downloadBtn": "⬇ Salvar como PNG",
    "toggleSettingsBtn": "⚙ Configurações",
    "mapWord": "Mapa",
    "fieldsWord": "campos",
    "pngError": "A exportação para PNG falhou. Alternativa: clique com o botão direito no mapa → \"Salvar imagem como\".",
    "options": {
      "aus": "Desligado",
      "mitte": "Centro",
      "oben": "Cima",
      "unten": "Baixo",
      "links": "Esquerda",
      "rechts": "Direita",
      "oben-links": "Cima esquerda",
      "oben-rechts": "Cima direita",
      "unten-links": "Baixo esquerda",
      "unten-rechts": "Baixo direita"
    },
    "pageTitle": "Oficina de Mapas",
    "heading": "D&D Helper",
    "indexSubtitle": "Sua jornada começa com um mapa",
    "description": "Crie o seu próprio mundo de fantasia — com montanhas, florestas, rios e assentamentos. Cada mapa é único, reproduzível e pronto para a sua próxima aventura.",
    "buttonText": "Ir para o Mapa",
    "footer": "Oficina de Mapas"
  },
  "ro": {
    "nativeName": "Română",
    "dir": "ltr",
    "title": "Harta Regatului",
    "subtitle": "O hartă fantastică desenată de mână: generată aleatoriu, cu munți, mare, pădure, deșert și un râu – complet personalizabilă după preferințele tale.",
    "generateBtn": "⚔ Generează o hartă nouă",
    "downloadBtn": "⬇ Salvează ca PNG",
    "toggleSettingsBtn": "⚙ Setări",
    "mapWord": "Hartă",
    "fieldsWord": "câmpuri",
    "pngError": "Exportul PNG a eșuat. Alternativ: click dreapta pe hartă → \"Salvează imaginea ca\".",
    "options": {
      "aus": "Dezactivat",
      "mitte": "Centru",
      "oben": "Sus",
      "unten": "Jos",
      "links": "Stânga",
      "rechts": "Dreapta",
      "oben-links": "Sus stânga",
      "oben-rechts": "Sus dreapta",
      "unten-links": "Jos stânga",
      "unten-rechts": "Jos dreapta"
    },
    "pageTitle": "Atelierul de Hărți",
    "heading": "D&D Helper",
    "indexSubtitle": "Călătoria ta începe cu o hartă",
    "description": "Creează-ți propria lume fantastică — cu munți, păduri, râuri și așezări. Fiecare hartă este unică, reproductibilă și pregătită pentru următoarea ta aventură.",
    "buttonText": "Spre Hartă",
    "footer": "Atelierul de Hărți"
  },
  "ru": {
    "nativeName": "Русский",
    "dir": "ltr",
    "title": "Карта королевства",
    "subtitle": "Рисованная фэнтезийная карта: генерируется случайным образом, с горами, морем, лесом, пустыней и рекой — полностью настраивается по вашему желанию.",
    "generateBtn": "⚔ Создать новую карту",
    "downloadBtn": "⬇ Сохранить как PNG",
    "toggleSettingsBtn": "⚙ Настройки",
    "mapWord": "Карта",
    "fieldsWord": "клеток",
    "pngError": "Экспорт в PNG не удался. Альтернатива: щёлкните правой кнопкой по карте → \"Сохранить изображение как\".",
    "options": {
      "aus": "Выкл",
      "mitte": "Центр",
      "oben": "Сверху",
      "unten": "Снизу",
      "links": "Слева",
      "rechts": "Справа",
      "oben-links": "Сверху слева",
      "oben-rechts": "Сверху справа",
      "unten-links": "Снизу слева",
      "unten-rechts": "Снизу справа"
    },
    "pageTitle": "Мастерская Карт",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоё путешествие начинается с карты",
    "description": "Создай свой собственный фэнтезийный мир — с горами, лесами, реками и поселениями. Каждая карта уникальна, воспроизводима и готова для твоего следующего приключения.",
    "buttonText": "К Карте",
    "footer": "Мастерская Карт"
  },
  "sk": {
    "nativeName": "Slovenčina",
    "dir": "ltr",
    "title": "Mapa kráľovstva",
    "subtitle": "Ručne kreslená fantasy mapa: náhodne generovaná, s horami, morom, lesom, púšťou a riekou – plne prispôsobiteľná podľa vašich predstáv.",
    "generateBtn": "⚔ Vygenerovať novú mapu",
    "downloadBtn": "⬇ Uložiť ako PNG",
    "toggleSettingsBtn": "⚙ Nastavenia",
    "mapWord": "Mapa",
    "fieldsWord": "polí",
    "pngError": "Export do PNG zlyhal. Alternatívne: kliknite pravým tlačidlom na mapu → \"Uložiť obrázok ako\".",
    "options": {
      "aus": "Vypnuté",
      "mitte": "Stred",
      "oben": "Hore",
      "unten": "Dole",
      "links": "Vľavo",
      "rechts": "Vpravo",
      "oben-links": "Hore vľavo",
      "oben-rechts": "Hore vpravo",
      "unten-links": "Dole vľavo",
      "unten-rechts": "Dole vpravo"
    },
    "pageTitle": "Dielňa Máp",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoja cesta začína mapou",
    "description": "Vytvor si vlastný fantasy svet — s horami, lesmi, riekami a osadami. Každá mapa je jedinečná, reprodukovateľná a pripravená na tvoje ďalšie dobrodružstvo.",
    "buttonText": "K Mape",
    "footer": "Dielňa Máp"
  },
  "sl": {
    "nativeName": "Slovenščina",
    "dir": "ltr",
    "title": "Zemljevid kraljestva",
    "subtitle": "Ročno narisan fantazijski zemljevid: naključno ustvarjen, z gorami, morjem, gozdom, puščavo in reko – v celoti prilagodljiv vašim željam.",
    "generateBtn": "⚔ Ustvari nov zemljevid",
    "downloadBtn": "⬇ Shrani kot PNG",
    "toggleSettingsBtn": "⚙ Nastavitve",
    "mapWord": "Zemljevid",
    "fieldsWord": "polj",
    "pngError": "Izvoz v PNG ni uspel. Druga možnost: desni klik na zemljevid → \"Shrani sliko kot\".",
    "options": {
      "aus": "Izklopljeno",
      "mitte": "Sredina",
      "oben": "Zgoraj",
      "unten": "Spodaj",
      "links": "Levo",
      "rechts": "Desno",
      "oben-links": "Zgoraj levo",
      "oben-rechts": "Zgoraj desno",
      "unten-links": "Spodaj levo",
      "unten-rechts": "Spodaj desno"
    },
    "pageTitle": "Delavnica Zemljevidov",
    "heading": "D&D Helper",
    "indexSubtitle": "Tvoje potovanje se začne z zemljevidom",
    "description": "Ustvari svoj lastni fantazijski svet — z gorami, gozdovi, rekami in naselji. Vsak zemljevid je edinstven, ponovljiv in pripravljen za tvojo naslednjo pustolovščino.",
    "buttonText": "Na Zemljevid",
    "footer": "Delavnica Zemljevidov"
  },
  "sq": {
    "nativeName": "Shqip",
    "dir": "ltr",
    "title": "Harta e Mbretërisë",
    "subtitle": "Një hartë fantazie e vizatuar me dorë: e krijuar rastësisht, me male, det, pyll, shkretëtirë dhe një lumë – plotësisht e personalizueshme sipas dëshirës suaj.",
    "generateBtn": "⚔ Krijo hartë të re",
    "downloadBtn": "⬇ Ruaj si PNG",
    "toggleSettingsBtn": "⚙ Cilësimet",
    "mapWord": "Harta",
    "fieldsWord": "fusha",
    "pngError": "Eksportimi PNG dështoi. Alternativa: klikoni me të djathtën mbi hartë → \"Ruaj imazhin si\".",
    "options": {
      "aus": "Fikur",
      "mitte": "Qendër",
      "oben": "Sipër",
      "unten": "Poshtë",
      "links": "Majtas",
      "rechts": "Djathtas",
      "oben-links": "Sipër majtas",
      "oben-rechts": "Sipër djathtas",
      "unten-links": "Poshtë majtas",
      "unten-rechts": "Poshtë djathtas"
    },
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map",
    "footer": "Map Workshop"
  },
  "sr": {
    "nativeName": "Српски",
    "dir": "ltr",
    "title": "Карта краљевства",
    "subtitle": "Ручно цртана фантастична карта: насумично генерисана, са планинама, морем, шумом, пустињом и реком – потпуно прилагодљива вашим жељама.",
    "generateBtn": "⚔ Генериши нову карту",
    "downloadBtn": "⬇ Сачувај као PNG",
    "toggleSettingsBtn": "⚙ Подешавања",
    "mapWord": "Карта",
    "fieldsWord": "поља",
    "pngError": "Извоз у PNG није успео. Алтернативно: десни клик на карту → \"Сачувај слику као\".",
    "options": {
      "aus": "Искључено",
      "mitte": "Средина",
      "oben": "Горе",
      "unten": "Доле",
      "links": "Лево",
      "rechts": "Десно",
      "oben-links": "Горе лево",
      "oben-rechts": "Горе десно",
      "unten-links": "Доле лево",
      "unten-rechts": "Доле десно"
    },
    "pageTitle": "Radionica Mapa",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоје путовање почиње мапом",
    "description": "Направи свој сопствени фантастични свет — са планинама, шумама, рекама и насељима. Свака мапа је јединствена, репродукована и спремна за твоју следећу авантуру.",
    "buttonText": "На Мапу",
    "footer": "Radionica Mapa"
  },
  "sv": {
    "nativeName": "Svenska",
    "dir": "ltr",
    "title": "Kungarikets karta",
    "subtitle": "En handritad fantasikarta: slumpmässigt genererad, med berg, hav, skog, öken och en flod – helt anpassningsbar efter dina önskemål.",
    "generateBtn": "⚔ Generera ny karta",
    "downloadBtn": "⬇ Spara som PNG",
    "toggleSettingsBtn": "⚙ Inställningar",
    "mapWord": "Karta",
    "fieldsWord": "fält",
    "pngError": "PNG-export misslyckades. Alternativt: högerklicka på kartan → \"Spara bild som\".",
    "options": {
      "aus": "Av",
      "mitte": "Mitten",
      "oben": "Topp",
      "unten": "Botten",
      "links": "Vänster",
      "rechts": "Höger",
      "oben-links": "Topp vänster",
      "oben-rechts": "Topp höger",
      "unten-links": "Botten vänster",
      "unten-rechts": "Botten höger"
    },
    "pageTitle": "Kartverkstad",
    "heading": "D&D Helper",
    "indexSubtitle": "Din resa börjar med en karta",
    "description": "Skapa din egen fantasyvärld — med berg, skogar, floder och bosättningar. Varje karta är unik, reproducerbar och redo för ditt nästa äventyr.",
    "buttonText": "Till Kartan",
    "footer": "Kartverkstad"
  },
  "sw": {
    "nativeName": "Kiswahili",
    "dir": "ltr",
    "title": "Ramani ya Ufalme",
    "subtitle": "Ramani ya kubuni iliyochorwa kwa mkono: inatengenezwa kwa nasibu, ikiwa na milima, bahari, msitu, jangwa na mto – inabadilishwa kikamilifu kulingana na matakwa yako.",
    "generateBtn": "⚔ Tengeneza Ramani Mpya",
    "downloadBtn": "⬇ Hifadhi kama PNG",
    "toggleSettingsBtn": "⚙ Mipangilio",
    "mapWord": "Ramani",
    "fieldsWord": "mashamba",
    "pngError": "Uhamishaji wa PNG umeshindwa. Vinginevyo: bofya kulia kwenye ramani → \"Hifadhi picha kama\".",
    "options": {
      "aus": "Imezimwa",
      "mitte": "Katikati",
      "oben": "Juu",
      "unten": "Chini",
      "links": "Kushoto",
      "rechts": "Kulia",
      "oben-links": "Juu kushoto",
      "oben-rechts": "Juu kulia",
      "unten-links": "Chini kushoto",
      "unten-rechts": "Chini kulia"
    },
    "pageTitle": "Karakana ya Ramani",
    "heading": "D&D Helper",
    "indexSubtitle": "Safari yako inaanza na ramani",
    "description": "Unda ulimwengu wako wa kubuni — wenye milima, misitu, mito na makazi. Kila ramani ni ya kipekee, inayoweza kutolewa tena, na tayari kwa ajili ya safari yako ijayo.",
    "buttonText": "Nenda kwenye Ramani",
    "footer": "Karakana ya Ramani"
  },
  "ta": {
    "nativeName": "தமிழ்",
    "dir": "ltr",
    "title": "அரசின் வரைபடம்",
    "subtitle": "கையால் வரையப்பட்ட ஒரு கற்பனை வரைபடம்: சீரற்ற முறையில் உருவாக்கப்பட்டது, மலைகள், கடல், காடு, பாலைவனம் மற்றும் ஒரு ஆற்றுடன் – உங்கள் விருப்பத்திற்கு ஏற்ப முழுமையாக தனிப்பயனாக்கக்கூடியது.",
    "generateBtn": "⚔ புதிய வரைபடத்தை உருவாக்கு",
    "downloadBtn": "⬇ PNG ஆக சேமி",
    "toggleSettingsBtn": "⚙ அமைப்புகள்",
    "mapWord": "வரைபடம்",
    "fieldsWord": "வயல்கள்",
    "pngError": "PNG ஏற்றுமதி தோல்வியடைந்தது. மாற்றாக: வரைபடத்தில் வலது கிளிக் செய்யவும் → \"படத்தை இப்படி சேமி\".",
    "options": {
      "aus": "ஆஃப்",
      "mitte": "மையம்",
      "oben": "மேலே",
      "unten": "கீழே",
      "links": "இடது",
      "rechts": "வலது",
      "oben-links": "மேலே இடது",
      "oben-rechts": "மேலே வலது",
      "unten-links": "கீழே இடது",
      "unten-rechts": "கீழே வலது"
    },
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map",
    "footer": "Map Workshop"
  },
  "te": {
    "nativeName": "తెలుగు",
    "dir": "ltr",
    "title": "రాజ్యం యొక్క పటం",
    "subtitle": "చేతితో గీసిన కల్పిత పటం: యాదృచ్ఛికంగా రూపొందించబడింది, పర్వతాలు, సముద్రం, అడవి, ఎడారి మరియు నదితో – మీ ఇష్టానికి అనుగుణంగా పూర్తిగా అనుకూలీకరించదగినది.",
    "generateBtn": "⚔ కొత్త పటం రూపొందించండి",
    "downloadBtn": "⬇ PNGగా సేవ్ చేయండి",
    "toggleSettingsBtn": "⚙ సెట్టింగ్‌లు",
    "mapWord": "పటం",
    "fieldsWord": "క్షేత్రాలు",
    "pngError": "PNG ఎగుమతి విఫలమైంది. ప్రత్యామ్నాయంగా: పటంపై కుడి-క్లిక్ చేయండి → \"చిత్రాన్ని ఇలా సేవ్ చేయండి\".",
    "options": {
      "aus": "ఆఫ్",
      "mitte": "మధ్య",
      "oben": "పైన",
      "unten": "కింద",
      "links": "ఎడమ",
      "rechts": "కుడి",
      "oben-links": "పైన ఎడమ",
      "oben-rechts": "పైన కుడి",
      "unten-links": "కింద ఎడమ",
      "unten-rechts": "కింద కుడి"
    },
    "pageTitle": "Map Workshop",
    "heading": "D&D Helper",
    "indexSubtitle": "Your journey begins with a map",
    "description": "Create your own fantasy world — with mountains, forests, rivers, and settlements. Every map is unique, reproducible, and ready for your next adventure.",
    "buttonText": "To the Map",
    "footer": "Map Workshop"
  },
  "th": {
    "nativeName": "ไทย",
    "dir": "ltr",
    "title": "Map of the Kingdom",
    "subtitle": "A hand-drawn fantasy map: randomly generated, with mountains, sea, forest, desert and a river – fully customisable to your liking.",
    "generateBtn": "⚔ Generate New Map",
    "downloadBtn": "⬇ Save as PNG",
    "toggleSettingsBtn": "⚙ Settings",
    "copySettingsBtn": "📋 Copy",
    "shareToggleBtn": "🔗 Share",
    "mapWord": "Map",
    "fieldsWord": "fields",
    "pngError": "PNG export failed. Alternatively: right-click the map → \"Save image as\".",
    "options": {
      "aus": "Off",
      "mitte": "Center",
      "oben": "Top",
      "unten": "Bottom",
      "links": "Left",
      "rechts": "Right",
      "oben-links": "Top left",
      "oben-rechts": "Top right",
      "unten-links": "Bottom left",
      "unten-rechts": "Bottom right"
    },
    "pageTitle": "โรงงานแผนที่",
    "heading": "D&D Helper",
    "indexSubtitle": "การเดินทางของคุณเริ่มต้นด้วยแผนที่",
    "description": "สร้างโลกแฟนตาซีของคุณเอง — พร้อมภูเขา ป่าไม้ แม่น้ำ และถิ่นฐาน แผนที่ทุกแผ่นมีเอกลักษณ์เฉพาะตัว ทำซ้ำได้ และพร้อมสำหรับการผจญภัยครั้งต่อไปของคุณ",
    "buttonText": "ไปที่แผนที่",
    "footer": "โรงงานแผนที่"
  },
  "tr": {
    "nativeName": "Türkçe",
    "dir": "ltr",
    "title": "Krallığın Haritası",
    "subtitle": "Elle çizilmiş bir fantezi haritası: rastgele oluşturulur, dağlar, deniz, orman, çöl ve bir nehir ile – tamamen isteğinize göre özelleştirilebilir.",
    "generateBtn": "⚔ Yeni Harita Oluştur",
    "downloadBtn": "⬇ PNG Olarak Kaydet",
    "toggleSettingsBtn": "⚙ Ayarlar",
    "mapWord": "Harita",
    "fieldsWord": "alan",
    "pngError": "PNG dışa aktarma başarısız oldu. Alternatif olarak: haritaya sağ tıklayın → \"Resmi farklı kaydet\".",
    "options": {
      "aus": "Kapalı",
      "mitte": "Merkez",
      "oben": "Üst",
      "unten": "Alt",
      "links": "Sol",
      "rechts": "Sağ",
      "oben-links": "Üst sol",
      "oben-rechts": "Üst sağ",
      "unten-links": "Alt sol",
      "unten-rechts": "Alt sağ"
    },
    "pageTitle": "Harita Atölyesi",
    "heading": "D&D Helper",
    "indexSubtitle": "Yolculuğun bir haritayla başlıyor",
    "description": "Dağlar, ormanlar, nehirler ve yerleşimlerle kendi fantezi dünyanı yarat. Her harita benzersiz, tekrar üretilebilir ve bir sonraki maceran için hazır.",
    "buttonText": "Haritaya Git",
    "footer": "Harita Atölyesi"
  },
  "uk": {
    "nativeName": "Українська",
    "dir": "ltr",
    "title": "Карта королівства",
    "subtitle": "Мальована вручну фентезійна карта: генерується випадковим чином, з горами, морем, лісом, пустелею та річкою – повністю налаштовується за вашим бажанням.",
    "generateBtn": "⚔ Створити нову карту",
    "downloadBtn": "⬇ Зберегти як PNG",
    "toggleSettingsBtn": "⚙ Налаштування",
    "mapWord": "Карта",
    "fieldsWord": "клітинок",
    "pngError": "Експорт у PNG не вдався. Альтернатива: клацніть правою кнопкою миші по карті → \"Зберегти зображення як\".",
    "options": {
      "aus": "Вимкнено",
      "mitte": "Центр",
      "oben": "Зверху",
      "unten": "Знизу",
      "links": "Зліва",
      "rechts": "Справа",
      "oben-links": "Зверху зліва",
      "oben-rechts": "Зверху справа",
      "unten-links": "Знизу зліва",
      "unten-rechts": "Знизу справа"
    },
    "pageTitle": "Майстерня Карт",
    "heading": "D&D Helper",
    "indexSubtitle": "Твоя подорож починається з карти",
    "description": "Створи власний фентезійний світ — з горами, лісами, річками та поселеннями. Кожна карта унікальна, відтворювана й готова до твоєї наступної пригоди.",
    "buttonText": "До Карти",
    "footer": "Майстерня Карт"
  },
  "ur": {
    "nativeName": "اردو",
    "dir": "rtl",
    "title": "بادشاہی کا نقشہ",
    "subtitle": "ہاتھ سے بنایا گیا ایک فنتاسی نقشہ: بے ترتیب طور پر تیار کیا گیا، پہاڑوں، سمندر، جنگل، صحرا اور ایک دریا کے ساتھ – آپ کی مرضی کے مطابق مکمل طور پر قابل ترتیب۔",
    "generateBtn": "⚔ نیا نقشہ بنائیں",
    "downloadBtn": "⬇ PNG کے طور پر محفوظ کریں",
    "toggleSettingsBtn": "⚙ ترتیبات",
    "mapWord": "نقشہ",
    "fieldsWord": "کھیت",
    "pngError": "PNG ایکسپورٹ ناکام ہو گیا۔ متبادل کے طور پر: نقشے پر دائیں کلک کریں → \"تصویر کو محفوظ کریں بطور\"۔",
    "options": {
      "aus": "بند",
      "mitte": "وسط",
      "oben": "اوپر",
      "unten": "نیچے",
      "links": "بائیں",
      "rechts": "دائیں",
      "oben-links": "اوپر بائیں",
      "oben-rechts": "اوپر دائیں",
      "unten-links": "نیچے بائیں",
      "unten-rechts": "نیچے دائیں"
    },
    "pageTitle": "نقشہ ورکشاپ",
    "heading": "D&D Helper",
    "indexSubtitle": "آپ کا سفر ایک نقشے سے شروع ہوتا ہے",
    "description": "پہاڑوں، جنگلات، دریاؤں اور بستیوں کے ساتھ اپنی خیالی دنیا بنائیں۔ ہر نقشہ منفرد، دوبارہ قابلِ تخلیق اور آپ کی اگلی مہم جوئی کے لیے تیار ہے۔",
    "buttonText": "نقشے پر جائیں",
    "footer": "نقشہ ورکشاپ"
  },
  "vi": {
    "nativeName": "Tiếng Việt",
    "dir": "ltr",
    "title": "Bản đồ Vương quốc",
    "subtitle": "Một bản đồ giả tưởng được vẽ tay: được tạo ngẫu nhiên, với núi, biển, rừng, sa mạc và một con sông – hoàn toàn có thể tùy chỉnh theo ý thích của bạn.",
    "generateBtn": "⚔ Tạo Bản Đồ Mới",
    "downloadBtn": "⬇ Lưu dưới dạng PNG",
    "toggleSettingsBtn": "⚙ Cài đặt",
    "mapWord": "Bản đồ",
    "fieldsWord": "ô",
    "pngError": "Xuất PNG không thành công. Hoặc: nhấp chuột phải vào bản đồ → \"Lưu hình ảnh thành\".",
    "options": {
      "aus": "Tắt",
      "mitte": "Giữa",
      "oben": "Trên",
      "unten": "Dưới",
      "links": "Trái",
      "rechts": "Phải",
      "oben-links": "Trên trái",
      "oben-rechts": "Trên phải",
      "unten-links": "Dưới trái",
      "unten-rechts": "Dưới phải"
    },
    "pageTitle": "Xưởng Bản Đồ",
    "heading": "D&D Helper",
    "indexSubtitle": "Hành trình của bạn bắt đầu với một tấm bản đồ",
    "description": "Tạo nên thế giới giả tưởng của riêng bạn — với núi non, rừng rậm, sông ngòi và khu định cư. Mỗi bản đồ đều độc nhất, có thể tái tạo và sẵn sàng cho cuộc phiêu lưu tiếp theo.",
    "buttonText": "Đến Bản Đồ",
    "footer": "Xưởng Bản Đồ"
  },
  "zh": {
    "nativeName": "中文",
    "dir": "ltr",
    "title": "王国地图",
    "subtitle": "一张手绘的奇幻地图：随机生成，包含山脉、海洋、森林、沙漠和河流——完全可根据你的喜好自定义。",
    "generateBtn": "⚔ 生成新地图",
    "downloadBtn": "⬇ 保存为PNG",
    "toggleSettingsBtn": "⚙ 设置",
    "mapWord": "地图",
    "fieldsWord": "地块",
    "pngError": "PNG导出失败。可以尝试：右键点击地图 →\"图片另存为\"。",
    "options": {
      "aus": "关闭",
      "mitte": "中间",
      "oben": "上方",
      "unten": "下方",
      "links": "左侧",
      "rechts": "右侧",
      "oben-links": "左上",
      "oben-rechts": "右上",
      "unten-links": "左下",
      "unten-rechts": "右下"
    },
    "pageTitle": "地图工坊",
    "heading": "D&D Helper",
    "indexSubtitle": "你的旅程从一张地图开始",
    "description": "创造属于你自己的奇幻世界——包含山脉、森林、河流与聚落。每张地图都是独一无二、可复现的，随时准备好迎接你的下一场冒险。",
    "buttonText": "查看地图",
    "footer": "地图工坊"
  }
};
